// diseases-data.js
// Companion data for the Prompt Builder's "Build by Disease" mode.
// Source: disease-list.md — 18 subjects, each with Common / Less Common / Rare tiers.
// Keys must match SUBJECTS[i].title exactly (see courseware-data.js) so the
// prompt builder can cross-reference subject -> chapters -> diseases.
// NOTE: Each tier expanded to ~20 entries (doubled from original 10).

const DISEASES = {
  "Anatomy": {
    common: ["Inguinal hernia (indirect/direct)","Varicose veins","Cervical rib","Bicornuate uterus / uterine anomalies","Meckel's diverticulum","Cleft lip and palate","Undescended testis (cryptorchidism)","Spina bifida occulta","Accessory/supernumerary breast (polymastia)","Flat foot (pes planus)","Pectus excavatum","Pectus carinatum","Umbilical hernia","Hydrocele","Congenital torticollis (wry neck)","Preauricular sinus/tag","Branchial cleft cyst","Thyroglossal duct cyst","Ectopic kidney","Bifid uvula"],
    lessCommon: ["Situs inversus","Horseshoe kidney","Polycystic kidney (anatomical correlation)","Klippel-Feil syndrome","Sprengel's deformity","Congenital diaphragmatic hernia","Persistent Mullerian duct syndrome","Coarctation of aorta (anatomical basis)","Double ureter / duplex collecting system","Amelia / phocomelia (limb anomalies)","Poland syndrome","Diaphragmatic eventration","Malrotation of the gut","Retrocaval ureter","Persistent left superior vena cava","Accessory spleen","Bicuspid aortic valve","Azygos continuation of inferior vena cava","Double inferior vena cava","Congenital absence of pericardium"],
    rare: ["Situs ambiguus","Ectopia cordis","Conjoined twins (anatomical basis)","Sirenomelia","Cyclopia","Rachischisis","Persistent truncus arteriosus (anatomical)","Agenesis of corpus callosum","Dextrocardia with situs solitus","Polydactyly/syndactyly complex variants","Kartagener syndrome (anatomical basis)","VACTERL association","Holoprosencephaly","Amniotic band syndrome","Exstrophy of bladder","Omphalocele","Gastroschisis","Anencephaly","Absent pulmonary valve syndrome","Scimitar syndrome"]
  },
  "Physiology": {
    common: ["Hypertension (physiological basis)","Anemia (physiological classification)","Hypoxia (types)","Dehydration / fluid imbalance","Fatigue/muscle cramps (electrolyte-related)","Menstrual irregularities (physiological)","Jet lag / circadian rhythm disturbance","Altitude sickness (hypoxia adaptation)","Heat exhaustion","Vasovagal syncope","Hyperventilation syndrome","Motion sickness","Hypoglycemia (physiological)","Hyperkalemia (physiological basis)","Hyponatremia (physiological basis)","Metabolic acidosis (compensatory physiology)","Metabolic alkalosis (compensatory physiology)","Orthostatic hypotension","Cold-induced diuresis","Exercise-induced hyperthermia"],
    lessCommon: ["Diabetes insipidus (physiological)","SIADH (physiological)","Decompression sickness","Chronic mountain sickness","Ondine's curse (central hypoventilation)","Familial periodic paralysis","Malignant hyperthermia","Reflex sympathetic dystrophy","Postural orthostatic tachycardia syndrome (POTS)","Exercise-induced bronchospasm","Renal tubular acidosis (physiological)","Bartter syndrome (physiological)","Gitelman syndrome (physiological)","Cheyne-Stokes breathing","Baroreceptor reflex failure","Autonomic dysreflexia","Cold agglutinin physiology","Heat stroke (physiological failure)","High-altitude pulmonary edema","High-altitude cerebral edema"],
    rare: ["Congenital insensitivity to pain","Guillain-Barré related autonomic dysfunction","Central pontine myelinolysis (physiological correlate)","Batten disease (metabolic/physiological)","Familial dysautonomia (Riley-Day syndrome)","Andersen-Tawil syndrome","Brugada syndrome (channelopathy)","Long QT syndrome","Catecholaminergic polymorphic VT","Primary hyperaldosteronism (physiological)","Liddle syndrome","Pseudohypoaldosteronism","Congenital central hypoventilation syndrome","Periodic fever syndromes (physiological basis)","Familial hemiplegic migraine (channelopathy)","Episodic ataxia (channelopathy)","Timothy syndrome","Short QT syndrome","Hyperekplexia","Paramyotonia congenita"]
  },
  "Biochemistry": {
    common: ["Diabetes mellitus (Type 1 & 2)","Obesity/dyslipidemia","Vitamin D deficiency (rickets/osteomalacia)","Iron deficiency anemia","Vitamin B12 deficiency","Gout (hyperuricemia)","Hypothyroidism (biochemical basis)","Metabolic syndrome","Fatty liver disease","Protein-energy malnutrition (Kwashiorkor/Marasmus)","Vitamin C deficiency (scurvy)","Vitamin A deficiency (biochemical)","Folate deficiency","Vitamin B1 deficiency (beriberi)","Vitamin B3 deficiency (pellagra)","Zinc deficiency","Hypercalcemia (biochemical basis)","Hypocalcemia (biochemical basis)","Hyperphosphatemia","Hypomagnesemia"],
    lessCommon: ["G6PD deficiency","Phenylketonuria (PKU)","Galactosemia","Wilson's disease","Hemochromatosis","Lactose intolerance","Homocystinuria","Maple syrup urine disease","Glycogen storage diseases (von Gierke's, Pompe's)","Familial hypercholesterolemia","Alpha-1 antitrypsin deficiency","Cystinuria","Tyrosinemia","Fructose intolerance (hereditary)","Ornithine transcarbamylase deficiency","Biotinidase deficiency","Carnitine deficiency","Medium-chain acyl-CoA dehydrogenase deficiency","Abetalipoproteinemia","Tangier disease"],
    rare: ["Tay-Sachs disease","Niemann-Pick disease","Gaucher's disease","Lesch-Nyhan syndrome","Alkaptonuria","Porphyrias (acute intermittent porphyria)","Fabry disease","Hurler syndrome (mucopolysaccharidosis)","Zellweger syndrome","Citrullinemia / urea cycle disorders","Krabbe disease","Metachromatic leukodystrophy","Refsum disease","Sandhoff disease","Pompe disease (infantile)","Menkes disease","I-cell disease","Congenital erythropoietic porphyria","Farber disease","Mucolipidosis"]
  },
  "Pathology": {
    common: ["Atherosclerosis","Tuberculosis (pathology)","Ischemic heart disease / myocardial infarction","Chronic inflammation-related fibrosis","Iron deficiency anemia (pathology)","Rheumatic heart disease","Cirrhosis of liver","Chronic kidney disease","Benign prostatic hyperplasia","Common carcinomas (breast, lung, cervix, oral)","Acute pancreatitis (pathology)","Peptic ulcer disease (pathology)","Pulmonary embolism (pathology)","Deep vein thrombosis (pathology)","Chronic gastritis","Fatty liver disease (pathology)","Osteoarthritis (pathology)","Chronic bronchitis (pathology)","Emphysema (pathology)","Colorectal polyps"],
    lessCommon: ["Amyloidosis","Sarcoidosis","Systemic lupus erythematosus","Hodgkin's and Non-Hodgkin's lymphoma","Multiple myeloma","Wegener's granulomatosis (GPA)","Polyarteritis nodosa","Hemolytic anemias (autoimmune, hereditary spherocytosis)","Nephrotic syndrome (minimal change, FSGS, membranous)","Leukemias (acute and chronic)","IgA nephropathy","Membranoproliferative glomerulonephritis","Myelodysplastic syndrome","Polycythemia vera","Essential thrombocythemia","Primary myelofibrosis","Giant cell arteritis","Takayasu arteritis","Churg-Strauss syndrome (EGPA)","Sjögren's syndrome"],
    rare: ["Langerhans cell histiocytosis","Goodpasture syndrome","Thrombotic thrombocytopenic purpura","Castleman disease","Mycosis fungoides","Kaposi sarcoma","Ewing's sarcoma","Retinoblastoma","Wilms tumor","Burkitt lymphoma","Angioimmunoblastic T-cell lymphoma","Waldenström macroglobulinemia","POEMS syndrome","Erdheim-Chester disease","Hemophagocytic lymphohistiocytosis","Rosai-Dorfman disease","Systemic mastocytosis","Amyloid light-chain (AL) amyloidosis","Familial Mediterranean fever (pathology)","Behçet's disease (pathology)"]
  },
  "Pharmacology": {
    common: ["Hypertension (drug therapy contexts)","Type 2 diabetes (drug therapy)","Peptic ulcer disease (drug-induced/treated)","Bronchial asthma (pharmacotherapy)","Bacterial infections (antibiotic contexts)","Pain management contexts (NSAID use)","Depression (antidepressant pharmacology)","Epilepsy (antiepileptic pharmacology)","Allergic rhinitis / anaphylaxis","Drug-induced peptic ulcer/gastritis","Hyperlipidemia (statin pharmacotherapy)","Congestive heart failure (drug therapy)","Arrhythmias (antiarrhythmic pharmacology)","Tuberculosis (drug therapy)","Anxiety disorders (anxiolytic pharmacology)","Nausea/vomiting (antiemetic pharmacology)","Constipation (laxative pharmacology)","Hypothyroidism (drug therapy)","Osteoporosis (drug therapy)","Glaucoma (drug therapy)"],
    lessCommon: ["Drug-induced hepatotoxicity","Steroid-induced Cushing's syndrome","Digoxin toxicity","Warfarin-induced bleeding/skin necrosis","Serotonin syndrome","Neuroleptic malignant syndrome","Aminoglycoside-induced ototoxicity/nephrotoxicity","Methotrexate toxicity","Drug-induced lupus","Stevens-Johnson syndrome / TEN (drug-induced)","Drug-induced pancreatitis","ACE inhibitor-induced angioedema","Beta-blocker-induced bronchospasm","Statin-induced myopathy/rhabdomyolysis","Heparin-induced thrombocytopenia","Tardive dyskinesia (antipsychotic-induced)","NSAID-induced nephropathy","Tetracycline-induced dental staining/photosensitivity","Fluoroquinolone-induced tendinopathy","Valproate-induced hepatotoxicity"],
    rare: ["Chloramphenicol-induced aplastic anemia / gray baby syndrome","Thalidomide-induced phocomelia","Reye's syndrome (aspirin-associated)","Halothane hepatitis","Isoniazid-induced peripheral neuropathy","Fixed drug eruption (severe forms)","Lithium-induced nephrogenic diabetes insipidus","Malignant hyperthermia (anesthetic drugs)","Ergotism","Black cohosh/herbal drug-induced hepatotoxicity","Amiodarone-induced pulmonary fibrosis","Amiodarone-induced thyroid dysfunction","Bleomycin-induced pulmonary fibrosis","Cisplatin-induced nephrotoxicity/ototoxicity","Vancomycin-induced red man syndrome","Clozapine-induced agranulocytosis","Methemoglobinemia (drug-induced)","Cocaine-induced cardiac ischemia (toxicological)","Digitalis-induced xanthopsia","Propylthiouracil-induced hepatotoxicity"]
  },
  "Microbiology": {
    common: ["Tuberculosis","Typhoid fever","Urinary tract infection (E. coli)","Streptococcal pharyngitis","Staphylococcal skin infections","Malaria","Dengue fever","Viral hepatitis (A, B, C)","HIV/AIDS","Fungal skin infections (dermatophytosis, candidiasis)","Cholera","Chickenpox (Varicella)","Measles","Mumps","Rubella","Herpes simplex infection","Influenza","Pneumococcal pneumonia","Whooping cough (Pertussis)","Salmonellosis"],
    lessCommon: ["Leptospirosis","Brucellosis","Diphtheria","Pertussis (whooping cough)","Tetanus","Rabies","Amoebiasis","Giardiasis","Cryptococcal meningitis","Mucormycosis","Toxoplasmosis","Cytomegalovirus infection","Epstein-Barr virus infection (infectious mononucleosis)","Listeriosis","Scrub typhus","Q fever","Aspergillosis","Blastomycosis","Coccidioidomycosis","Cysticercosis"],
    rare: ["Anthrax","Plague (Yersinia pestis)","Melioidosis","Nipah virus infection","Kyasanur Forest disease","Chikungunya (severe complications)","Cholera (severe outbreak forms)","Actinomycosis","Histoplasmosis","Prion diseases (Creutzfeldt-Jakob disease)","Ebola virus disease","Marburg virus disease","Lassa fever","Botulism","Diphtheria (severe systemic complications)","Tularemia","Whipple's disease","Progressive multifocal leukoencephalopathy","Human African trypanosomiasis","Rat-bite fever"]
  },
  "Forensic Medicine & Toxicology": {
    common: ["Organophosphate poisoning","Alcohol intoxication/dependence","Road traffic accident-related injuries","Burns (medicolegal aspects)","Snake bite (venomous)","Corrosive/acid poisoning","Firearm injuries (medicolegal)","Drowning","Hanging/asphyxial deaths","Domestic violence-related injuries","Blunt force trauma (medicolegal)","Sharp force injuries (stab wounds)","Suicide by poisoning (medicolegal)","Food poisoning (medicolegal)","Industrial accident injuries","Child abuse-related injuries","Strangulation (manual/ligature)","Postmortem interval estimation cases","Traffic fatality (pedestrian)","Chemical burns (occupational)"],
    lessCommon: ["Barbiturate/benzodiazepine poisoning","Opioid overdose","Kerosene/hydrocarbon poisoning","Rodenticide (zinc phosphide) poisoning","Carbon monoxide poisoning","Electrocution injuries","Heat stroke (medicolegal)","Scorpion sting","Aluminium phosphide poisoning","Sexual assault-related injury patterns","Copper sulfate poisoning","Datura poisoning","Insecticide (carbamate) poisoning","Methanol poisoning","Ethylene glycol poisoning","Paraquat poisoning","Cannabis intoxication (medicolegal)","Amphetamine/stimulant toxicity","Neonaticide/infant death investigation","Occupational lead poisoning (forensic)"],
    rare: ["Arsenic poisoning (chronic)","Lead poisoning (medicolegal)","Mercury poisoning","Thallium poisoning","Cyanide poisoning","Mushroom poisoning","Puffer fish (tetrodotoxin) poisoning","Radiation injury","Munchausen syndrome by proxy","Fetal death/infanticide medicolegal cases","Ricin poisoning","Strychnine poisoning","Digitalis poisoning (forensic)","Insulin homicide/overdose cases","Air embolism (forensic)","Spontaneous human combustion (forensic myth investigation)","Sudden infant death syndrome (forensic)","Excited delirium syndrome","Battered baby syndrome","Postmortem lividity anomaly cases"]
  },
  "Community Medicine": {
    common: ["Malnutrition (PEM, stunting, wasting)","Anemia (public health burden)","Diarrheal diseases (childhood)","Acute respiratory infections (childhood)","Tuberculosis (public health)","Vaccine-preventable diseases (measles, polio)","Hypertension (population screening)","Diabetes (population screening)","Maternal mortality-related conditions","Vector-borne diseases (malaria, dengue, filariasis)","Obesity (public health)","Cardiovascular disease (population burden)","Cervical cancer (screening programs)","Breast cancer (screening programs)","Neonatal mortality-related conditions","Adolescent reproductive health issues","Tobacco use-related disease burden","Alcohol use disorder (public health)","Road traffic injury (public health)","Mental health disorders (community burden)"],
    lessCommon: ["Iodine deficiency disorders (goiter)","Vitamin A deficiency (xerophthalmia)","Occupational lung diseases (silicosis, byssinosis)","Fluorosis","Leprosy (public health control)","HIV/AIDS (epidemiological)","Lymphatic filariasis","Japanese encephalitis","Rabies (public health control)","Tobacco-related diseases (population level)","Waterborne disease outbreaks (community)","Noise-induced hearing loss (occupational)","Pesticide exposure-related illness (agricultural)","Anemia in pregnancy (public health)","Zoonotic disease surveillance conditions","Air pollution-related respiratory disease","Sickle cell disease (community screening)","Thalassemia (community screening)","Hepatitis B (immunization programs)","Chikungunya outbreaks (community)"],
    rare: ["Guinea worm disease (dracunculiasis) — near eradicated","Yaws","Trachoma (blinding)","Kala-azar (visceral leishmaniasis)","Cholera outbreaks","Nipah virus outbreaks","Anthrax (occupational/zoonotic)","Radiation exposure disorders","Endemic fluorosis-related skeletal deformity","Minamata disease (mercury, environmental)","Itai-itai disease (cadmium poisoning)","Bhopal gas tragedy-related illness (methyl isocyanate exposure)","Podoconiosis","Buruli ulcer","Congenital rubella syndrome (eradication surveillance)","Neonatal tetanus (elimination surveillance)","Diphtheria resurgence (public health)","Lathyrism","Endemic goiter cretinism","Onchocerciasis (river blindness)"]
  },
  "Ophthalmology": {
    common: ["Refractive errors (myopia, hypermetropia, astigmatism)","Cataract","Conjunctivitis (bacterial/viral/allergic)","Diabetic retinopathy","Trachoma","Stye (hordeolum)","Dry eye disease","Pterygium","Corneal abrasion/foreign body","Chalazion","Blepharitis","Subconjunctival hemorrhage","Presbyopia","Amblyopia","Entropion/ectropion","Dacryocystitis","Episcleritis","Xerophthalmia (ophthalmic)","Hypertensive retinopathy (mild)","Allergic conjunctivitis (vernal)"],
    lessCommon: ["Glaucoma (primary open angle, angle closure)","Uveitis","Retinal detachment","Central retinal artery/vein occlusion","Squint (strabismus)","Keratoconus","Optic neuritis","Corneal ulcer (bacterial/fungal)","Endophthalmitis","Hypertensive retinopathy","Age-related macular degeneration","Diabetic macular edema","Herpes zoster ophthalmicus","Scleritis","Orbital cellulitis","Thyroid eye disease (Graves' ophthalmopathy)","Nystagmus (acquired)","Retinal vein occlusion (branch)","Vitreous hemorrhage","Papilledema"],
    rare: ["Retinoblastoma","Retinitis pigmentosa","Sympathetic ophthalmia","Orbital cellulitis (severe complications)","Congenital glaucoma (buphthalmos)","Marfan syndrome-related lens dislocation","Coats disease","Choroidal melanoma","Fuchs' endothelial dystrophy","Behçet's disease (ocular involvement)","Leber's hereditary optic neuropathy","Optic nerve glioma","Persistent fetal vasculature","Uveal melanoma (advanced)","Acanthamoeba keratitis","Sympathetic uveitis (post-traumatic)","Vogt-Koyanagi-Harada disease","Best disease (vitelliform dystrophy)","Congenital rubella cataract syndrome","Anophthalmia/microphthalmia"]
  },
  "Otorhinolaryngology (ENT)": {
    common: ["Otitis media (acute/chronic)","Sinusitis","Tonsillitis/pharyngitis","Allergic rhinitis","Epistaxis","Deviated nasal septum","Wax impaction (cerumen)","Foreign body in ear/nose","Hearing loss (conductive/sensorineural, age-related)","Laryngitis","Otitis externa","Common cold (upper respiratory infection)","Adenoiditis","Nasal furuncle","Snoring/obstructive sleep apnea (ENT)","Tinnitus","Perforated tympanic membrane (traumatic)","Acute pharyngitis (viral)","Salivary gland calculi (sialolithiasis)","Chronic rhinosinusitis"],
    lessCommon: ["Otosclerosis","Ménière's disease","Vocal cord nodules/polyps","Nasal polyposis","Peritonsillar abscess (quinsy)","Mastoiditis","Vestibular neuronitis","Laryngeal papillomatosis","Adenoid hypertrophy","Sudden sensorineural hearing loss","Retropharyngeal abscess","Epiglottitis (acute)","Ludwig's angina","Parotitis (non-mumps)","Cholesteatoma (uncomplicated)","Laryngomalacia","Vocal cord paralysis","Bell's palsy (ENT correlation)","Sialadenitis (chronic)","Allergic fungal sinusitis"],
    rare: ["Nasopharyngeal carcinoma","Laryngeal carcinoma","Acoustic neuroma","Cholesteatoma (complicated)","Juvenile angiofibroma","Wegener's granulomatosis (ENT presentation)","Ramsay Hunt syndrome","Glomus jugulare tumor","Rhinoscleroma","Necrotizing (malignant) otitis externa","Parapharyngeal space tumor","Esthesioneuroblastoma","Laryngeal amyloidosis","Sinonasal undifferentiated carcinoma","Cerebellopontine angle tumor (ENT presentation)","Choanal atresia","First branchial cleft anomaly","Rhinocerebral mucormycosis","Perilymph fistula","Otic capsule otosclerosis (far advanced)"]
  },
  "General Medicine": {
    common: ["Hypertension","Type 2 diabetes mellitus","Ischemic heart disease","Chronic obstructive pulmonary disease (COPD)","Bronchial asthma","Community-acquired pneumonia","Pulmonary tuberculosis","Peptic ulcer disease / GERD","Chronic kidney disease","Anemia (iron deficiency)","Urinary tract infection","Viral hepatitis (acute)","Dengue fever (uncomplicated)","Typhoid fever (clinical)","Hypothyroidism","Hyperthyroidism (Graves' disease)","Osteoarthritis (clinical)","Gout (clinical)","Migraine","Depression (clinical presentation)"],
    lessCommon: ["Congestive heart failure","Stroke (ischemic/hemorrhagic)","Chronic liver disease/cirrhosis","Rheumatoid arthritis","Systemic lupus erythematosus","Hypothyroidism/hyperthyroidism","Nephrotic/nephritic syndrome","Malaria (complicated)","Dengue (with warning signs)","Enteric (typhoid) fever with complications","Infective endocarditis","Pericarditis (acute)","Deep vein thrombosis (clinical)","Pulmonary embolism (clinical)","Chronic pancreatitis","Inflammatory bowel disease (Crohn's/UC)","Vitamin B12 deficiency (clinical anemia)","Sarcoidosis (clinical)","Sjögren's syndrome (clinical)","Polymyalgia rheumatica"],
    rare: ["HIV/AIDS with opportunistic infections","Systemic sclerosis (scleroderma)","Guillain-Barré syndrome","Myasthenia gravis","Addison's disease","Pheochromocytoma","Amyloidosis (systemic)","Wilson's disease (clinical)","Hemochromatosis (clinical)","Thrombotic thrombocytopenic purpura","Cushing's syndrome (endogenous)","Acromegaly","SIADH (clinical)","Multiple sclerosis","Systemic vasculitis (ANCA-associated)","Primary biliary cholangitis","Autoimmune hepatitis","Whipple's disease (clinical)","Familial Mediterranean fever (clinical)","Paraneoplastic syndromes"]
  },
  "General Surgery": {
    common: ["Acute appendicitis","Inguinal hernia","Gallstone disease/cholecystitis","Hemorrhoids","Peptic ulcer perforation","Breast lump (fibroadenoma/carcinoma workup)","Thyroid nodule/goiter","Intestinal obstruction","Wound infections/abscess","Varicose veins (surgical)","Anal fissure","Pilonidal sinus","Lipoma (surgical excision)","Sebaceous cyst","Umbilical hernia (surgical)","Femoral hernia","Diabetic foot ulcer (surgical)","Breast abscess","Skin and soft tissue abscess","Ganglion cyst"],
    lessCommon: ["Acute pancreatitis","Diabetic foot/gangrene","Perianal fistula","Peripheral arterial disease","Carcinoma stomach","Carcinoma colon/rectum","Splenic injury/rupture","Hydatid cyst (liver)","Thyroid carcinoma","Umbilical/incisional hernia","Achalasia cardia","Gastroesophageal reflux disease (surgical)","Rectal prolapse","Anal fistula (complex)","Chronic pancreatitis (surgical)","Choledochal cyst","Carcinoma esophagus","Carcinoma gallbladder","Splenomegaly (surgical workup)","Mesenteric ischemia"],
    rare: ["Carcinoid tumor","Gastrointestinal stromal tumor (GIST)","Pheochromocytoma (surgical)","Retroperitoneal sarcoma","Zollinger-Ellison syndrome","Boerhaave syndrome (esophageal rupture)","Meckel's diverticulitis","Volvulus (sigmoid/cecal)","Necrotizing fasciitis","Pancreatic pseudocyst with complications","Insulinoma","Pancreatic carcinoma (advanced)","Adrenal carcinoma","Desmoid tumor","Sistrunk-requiring thyroglossal fistula","Mirizzi syndrome","Klatskin tumor (cholangiocarcinoma)","Fournier's gangrene","Ogilvie syndrome (colonic pseudo-obstruction)","Peutz-Jeghers syndrome (surgical)"]
  },
  "Obstetrics & Gynaecology (OBG)": {
    common: ["Normal pregnancy/antenatal care conditions","Anemia in pregnancy","Pregnancy-induced hypertension/pre-eclampsia","Gestational diabetes","Menstrual disorders (menorrhagia, dysmenorrhea)","Polycystic ovarian syndrome (PCOS)","Uterine fibroids","Vaginal/pelvic infections","Postpartum hemorrhage","Ectopic pregnancy","Threatened/spontaneous abortion","Preterm labour","Urinary tract infection in pregnancy","Vaginal candidiasis","Bacterial vaginosis","Pelvic inflammatory disease","Cervical erosion/ectropion","Amenorrhea (secondary)","Menopausal syndrome","Ovarian cyst (functional)"],
    lessCommon: ["Eclampsia","Placenta previa","Abruptio placentae","Obstructed labour","Ovarian cysts/tumors (benign)","Endometriosis","Infertility (female factor)","Cervical intraepithelial neoplasia","Molar pregnancy (hydatidiform mole)","Rh isoimmunization","Intrauterine growth restriction","Oligohydramnios","Polyhydramnios","Twin pregnancy complications","Postpartum sepsis (puerperal fever)","Adenomyosis","Uterine prolapse","Premature rupture of membranes","Gestational trophoblastic disease (partial mole)","Fibroid degeneration (red degeneration in pregnancy)"],
    rare: ["Choriocarcinoma","Amniotic fluid embolism","Uterine rupture","Vasa previa","HELLP syndrome","Uterine inversion","Ovarian carcinoma","Cervical carcinoma (advanced)","Asherman's syndrome","Placenta accreta/percreta","Acute fatty liver of pregnancy","Peripartum cardiomyopathy","Sheehan syndrome","Placental abruption with DIC","Vulvar carcinoma","Fallopian tube carcinoma","Ovarian hyperstimulation syndrome","Cornual (interstitial) ectopic pregnancy","Uterine sarcoma","Meigs syndrome"]
  },
  "Paediatrics": {
    common: ["Acute respiratory infections","Acute diarrheal disease/dehydration","Protein-energy malnutrition","Neonatal jaundice","Vaccine-preventable diseases (measles, chickenpox)","Iron deficiency anemia","Febrile seizures","Bronchiolitis","Worm infestations","Vitamin D deficiency rickets","Neonatal sepsis (early presentation)","Acute tonsillitis (paediatric)","Croup (laryngotracheobronchitis)","Hand-foot-mouth disease","Impetigo (paediatric)","Otitis media (paediatric)","Urinary tract infection (paediatric)","Failure to thrive","Constipation (functional, paediatric)","Atopic dermatitis (paediatric)"],
    lessCommon: ["Congenital heart disease","Down syndrome","Nephrotic syndrome (childhood)","Acute rheumatic fever","Cerebral palsy","Neonatal sepsis","Respiratory distress syndrome (preterm)","Autism spectrum disorder","ADHD","Thalassemia","Henoch-Schönlein purpura","Idiopathic thrombocytopenic purpura (childhood)","Intussusception","Pyloric stenosis (infantile)","Hirschsprung's disease","Congenital hypothyroidism","G6PD deficiency (neonatal jaundice)","Bronchopulmonary dysplasia","Necrotizing enterocolitis","Juvenile idiopathic arthritis"],
    rare: ["Acute lymphoblastic leukemia","Wilms tumor","Neuroblastoma","Kawasaki disease","Duchenne muscular dystrophy","Biliary atresia","Congenital adrenal hyperplasia","SCID (severe combined immunodeficiency)","Reye's syndrome","Hemolytic uremic syndrome","Retinoblastoma (paediatric)","Hepatoblastoma","Rett syndrome","Prader-Willi syndrome","Menkes disease (paediatric)","Osteogenesis imperfecta (paediatric)","Spinal muscular atrophy","Galactosemia (neonatal presentation)","Maple syrup urine disease (neonatal)","Congenital diaphragmatic hernia (neonatal)"]
  },
  "Orthopaedics": {
    common: ["Fractures (long bone — femur, tibia, radius/ulna)","Osteoarthritis","Low back pain / disc prolapse","Sprains and ligament injuries","Osteoporosis","Fracture clavicle","Dislocation shoulder","Cervical spondylosis","Plantar fasciitis","Frozen shoulder","Tennis elbow (lateral epicondylitis)","Fracture neck of femur","Meniscal tear (knee)","Ankle sprain","Rotator cuff injury","Carpal tunnel syndrome","Bunion (hallux valgus)","Trigger finger","De Quervain's tenosynovitis","Colles' fracture"],
    lessCommon: ["Rheumatoid arthritis (orthopaedic aspects)","Osteomyelitis","Congenital talipes equinovarus (CTEV/clubfoot)","Developmental dysplasia of hip (DDH)","Septic arthritis","Ankylosing spondylitis","Avascular necrosis of femoral head","Rickets/osteomalacia (orthopaedic)","Scoliosis","Compartment syndrome","Slipped capital femoral epiphysis","Osgood-Schlatter disease","Tuberculosis of spine (Pott's disease)","Non-union of fracture","Malunion of fracture","Charcot joint (neuropathic arthropathy)","Torticollis (musculoskeletal)","Kienböck's disease","Freiberg's disease","Gouty arthritis (orthopaedic)"],
    rare: ["Osteosarcoma","Ewing's sarcoma","Osteogenesis imperfecta","Achondroplasia","Perthes disease","Marfan syndrome (skeletal)","Paget's disease of bone","Giant cell tumor of bone","Chondrosarcoma","Fibrous dysplasia","Osteopetrosis","Multiple hereditary exostoses","Osteoid osteoma","Enchondromatosis (Ollier disease)","Synovial sarcoma","Chordoma","Adamantinoma","Langerhans cell histiocytosis (bone)","Melorheostosis","Fibrodysplasia ossificans progressiva"]
  },
  "Dermatology": {
    common: ["Acne vulgaris","Eczema/atopic dermatitis","Fungal skin infections (tinea)","Scabies","Urticaria","Psoriasis","Contact dermatitis","Viral warts","Vitiligo","Alopecia (androgenetic/areata)","Pediculosis (lice infestation)","Molluscum contagiosum","Impetigo","Folliculitis","Melasma (dermatological)","Seborrheic keratosis","Callus/corn","Prickly heat (miliaria)","Chronic hand eczema","Tinea versicolor"],
    lessCommon: ["Herpes zoster","Lichen planus","Pemphigus vulgaris","Bullous pemphigoid","Leprosy (dermatological)","Syphilis (cutaneous manifestations)","Drug eruptions (fixed drug eruption, Stevens-Johnson)","Seborrheic dermatitis","Rosacea","Melasma","Discoid lupus erythematosus","Erythema nodosum","Erythema multiforme","Lichen sclerosus","Granuloma annulare","Nummular eczema","Hidradenitis suppurativa","Actinic keratosis","Keloid/hypertrophic scar","Photodermatitis"],
    rare: ["Toxic epidermal necrolysis","Mycosis fungoides","Xeroderma pigmentosum","Epidermolysis bullosa","Dermatitis herpetiformis","Necrobiosis lipoidica","Pyoderma gangrenosum","Cutaneous T-cell lymphoma","Acanthosis nigricans (paraneoplastic)","Sweet syndrome","Ichthyosis (congenital)","Darier's disease","Pemphigus foliaceus","Linear IgA bullous dermatosis","Porphyria cutanea tarda (dermatological)","Scleroderma (cutaneous, systemic sclerosis)","Necrolytic migratory erythema","Kaposi sarcoma (dermatological)","Erythroderma (exfoliative dermatitis)","Bazex syndrome"]
  },
  "Psychiatry": {
    common: ["Major depressive disorder","Generalized anxiety disorder","Alcohol use disorder","Insomnia","Somatoform disorders","Panic disorder","Adjustment disorder","Substance use disorder (tobacco/cannabis)","Post-traumatic stress disorder","Obsessive-compulsive disorder","Specific phobia","Acute stress reaction","Grief reaction (complicated)","Body dysmorphic disorder","Eating disorder (anorexia/bulimia)","Sleep disorder (parasomnias)","Hypochondriasis (illness anxiety disorder)","Cyclothymia","Dysthymia (persistent depressive disorder)","Nicotine dependence"],
    lessCommon: ["Schizophrenia","Bipolar affective disorder","Delirium","Dementia (Alzheimer's type)","Social anxiety disorder / phobias","Somatic symptom disorder","Conversion disorder","ADHD (psychiatric evaluation)","Personality disorders (borderline, antisocial)","Opioid dependence","Delusional disorder","Brief psychotic disorder","Vascular dementia","Frontotemporal dementia","Postpartum depression/psychosis","Alcohol withdrawal delirium (delirium tremens)","Substance-induced psychotic disorder","Trichotillomania","Gambling disorder","Intellectual disability (psychiatric assessment)"],
    rare: ["Catatonia","Schizoaffective disorder","Capgras syndrome","Cotard's syndrome","Dissociative identity disorder","Munchausen syndrome","Folie à deux (shared psychotic disorder)","Kleine-Levin syndrome","Neuroleptic malignant syndrome (psychiatric context)","De Clerambault syndrome (erotomania)","Fregoli syndrome","Ganser syndrome","Charles Bonnet syndrome","Othello syndrome (delusional jealousy)","Ekbom syndrome (delusional parasitosis)","Alien hand syndrome (psychiatric correlate)","Depersonalization-derealization disorder","Pica (severe/persistent)","Reduplicative paramnesia","Cotard-Capgras overlap syndrome"]
  },
  "Emergency Medicine": {
    common: ["Acute myocardial infarction","Trauma/polytrauma","Acute severe asthma","Anaphylaxis","Diabetic ketoacidosis","Acute stroke","Status epilepticus","Acute poisoning (organophosphate, drug overdose)","Snake bite envenomation","Acute gastroenteritis with dehydration","Acute abdomen (general presentation)","Hypertensive emergency","Acute pulmonary embolism (emergency)","Head injury (mild-moderate)","Foreign body airway obstruction","Acute urinary retention","Febrile seizure (emergency presentation)","Acute severe pain crisis (sickle cell)","Hypoglycemia (emergency)","Acute allergic reaction (non-anaphylactic)"],
    lessCommon: ["Cardiac arrest (arrhythmia-related)","Tension pneumothorax","Septic shock","Burns (major)","Hypoglycemic emergency","Acute pulmonary edema","Ectopic pregnancy rupture (emergency)","Heat stroke","Near-drowning","Acute abdomen (perforation/obstruction)","Diabetic hyperosmolar state","Acute compartment syndrome (emergency)","Traumatic hemothorax","Acute mesenteric ischemia (emergency)","Acute limb ischemia","Testicular torsion (emergency)","Acute epiglottitis (emergency)","Severe electrolyte derangement (hyperkalemia crisis)","Acute variceal bleeding","Status asthmaticus"],
    rare: ["Massive pulmonary embolism","Aortic dissection","Amniotic fluid embolism (emergency)","Thyroid storm","Myxedema coma","Addisonian crisis","Malignant hyperthermia (emergency)","Neuroleptic malignant syndrome (emergency)","Mass casualty/disaster trauma","Electrical injury with cardiac arrest","Cardiac tamponade (emergency)","Necrotizing fasciitis (emergency)","Traumatic aortic rupture","Fat embolism syndrome","Serotonin syndrome (emergency)","Anaphylactoid reaction to contrast media","Air embolism (emergency)","Toxic shock syndrome","Ruptured abdominal aortic aneurysm","Spontaneous pneumomediastinum"]
  }
};

if (typeof module !== 'undefined' && module.exports) module.exports = DISEASES;
