// diseases-data.js
// Companion data for the Prompt Builder's "Build by Disease" mode.
// Source: disease-list.md — 18 subjects, each with Common / Less Common / Rare tiers.
// Keys must match SUBJECTS[i].title exactly (see courseware-data.js) so the
// prompt builder can cross-reference subject -> chapters -> diseases.
// NOTE: Each tier expanded to ~40 entries (doubled again from 20).

const DISEASES = {
  "Anatomy": {
    "common": [
      "Inguinal hernia (indirect/direct)",
      "Varicose veins",
      "Cervical rib",
      "Bicornuate uterus / uterine anomalies",
      "Meckel's diverticulum",
      "Cleft lip and palate",
      "Undescended testis (cryptorchidism)",
      "Spina bifida occulta",
      "Accessory/supernumerary breast (polymastia)",
      "Flat foot (pes planus)",
      "Pectus excavatum",
      "Pectus carinatum",
      "Umbilical hernia",
      "Hydrocele",
      "Congenital torticollis (wry neck)",
      "Preauricular sinus/tag",
      "Branchial cleft cyst",
      "Thyroglossal duct cyst",
      "Ectopic kidney",
      "Bifid uvula",
      "Congenital hip dislocation (anatomical)",
      "Rectal prolapse (anatomical)",
      "Diastasis recti",
      "Bat ear (prominent pinna)",
      "Tongue tie (ankyloglossia)",
      "Webbed neck (anatomical)",
      "Simian crease (anatomical variant)",
      "Accessory nipple",
      "Duplex kidney (mild)",
      "Retrocecal appendix (anatomical variant)",
      "Mallet finger (anatomical)",
      "Trigger thumb (congenital)",
      "Bifid rib",
      "Sacralization of lumbar vertebra",
      "Lumbarization of sacral vertebra",
      "Persistent notochordal remnant",
      "Sternal foramen",
      "Wormian bones (anatomical variant)",
      "Accessory renal artery",
      "High-riding scapula (mild)"
    ],
    "lessCommon": [
      "Situs inversus",
      "Horseshoe kidney",
      "Polycystic kidney (anatomical correlation)",
      "Klippel-Feil syndrome",
      "Sprengel's deformity",
      "Congenital diaphragmatic hernia",
      "Persistent Mullerian duct syndrome",
      "Coarctation of aorta (anatomical basis)",
      "Double ureter / duplex collecting system",
      "Amelia / phocomelia (limb anomalies)",
      "Poland syndrome",
      "Diaphragmatic eventration",
      "Malrotation of the gut",
      "Retrocaval ureter",
      "Persistent left superior vena cava",
      "Accessory spleen",
      "Bicuspid aortic valve",
      "Azygos continuation of inferior vena cava",
      "Double inferior vena cava",
      "Congenital absence of pericardium",
      "Ectopic ureter",
      "Duplication of the gallbladder",
      "Left-sided inferior vena cava",
      "Circumaortic renal vein",
      "Congenital absence of vas deferens",
      "Persistent hyaloid artery",
      "Absent palmaris longus (anatomical variant)",
      "Cervical rib with vascular compression",
      "Median arcuate ligament syndrome",
      "Nutcracker syndrome (anatomical)",
      "May-Thurner syndrome (anatomical)",
      "Duplicated appendix",
      "Intestinal malfixation",
      "Anomalous origin of coronary artery",
      "Bridging vein anomaly",
      "Persistent sciatic artery",
      "Aberrant subclavian artery (arteria lusoria)",
      "Congenital pouch colon",
      "Accessory hepatic lobe",
      "Riedel's lobe of liver"
    ],
    "rare": [
      "Situs ambiguus",
      "Ectopia cordis",
      "Conjoined twins (anatomical basis)",
      "Sirenomelia",
      "Cyclopia",
      "Rachischisis",
      "Persistent truncus arteriosus (anatomical)",
      "Agenesis of corpus callosum",
      "Dextrocardia with situs solitus",
      "Polydactyly/syndactyly complex variants",
      "Kartagener syndrome (anatomical basis)",
      "VACTERL association",
      "Holoprosencephaly",
      "Amniotic band syndrome",
      "Exstrophy of bladder",
      "Omphalocele",
      "Gastroschisis",
      "Anencephaly",
      "Absent pulmonary valve syndrome",
      "Scimitar syndrome",
      "Pentalogy of Cantrell",
      "Body stalk anomaly",
      "Cloacal exstrophy",
      "Caudal regression syndrome",
      "Ectromelia (limb reduction defect)",
      "Fetus in fetu",
      "Craniopagus conjoined twins",
      "Polymelia",
      "Diprosopus",
      "Situs inversus with polysplenia",
      "Situs inversus with asplenia",
      "Heterotaxy syndrome",
      "Persistent cloaca",
      "Currarino triad",
      "Bladder duplication",
      "Uterus didelphys with double cervix",
      "OEIS complex",
      "Amelia with facial clefting",
      "Ectopic cordis with omphalocele",
      "Complete tracheal rings"
    ]
  },
  "Physiology": {
    "common": [
      "Hypertension (physiological basis)",
      "Anemia (physiological classification)",
      "Hypoxia (types)",
      "Dehydration / fluid imbalance",
      "Fatigue/muscle cramps (electrolyte-related)",
      "Menstrual irregularities (physiological)",
      "Jet lag / circadian rhythm disturbance",
      "Altitude sickness (hypoxia adaptation)",
      "Heat exhaustion",
      "Vasovagal syncope",
      "Hyperventilation syndrome",
      "Motion sickness",
      "Hypoglycemia (physiological)",
      "Hyperkalemia (physiological basis)",
      "Hyponatremia (physiological basis)",
      "Metabolic acidosis (compensatory physiology)",
      "Metabolic alkalosis (compensatory physiology)",
      "Orthostatic hypotension",
      "Cold-induced diuresis",
      "Exercise-induced hyperthermia",
      "Heat cramps",
      "Cold urticaria (physiological trigger)",
      "Post-exercise hypotension",
      "Valsalva-induced syncope",
      "Circadian sleep phase disorder",
      "Nocturnal polyuria (physiological)",
      "Physiological jaundice of newborn",
      "Lactic acidosis (exercise-induced)",
      "Hyperventilation-induced tetany",
      "Diving reflex-related bradycardia",
      "Cough syncope",
      "Micturition syncope",
      "Postprandial hypotension",
      "Exercise-associated hyponatremia",
      "Refeeding-related electrolyte shift",
      "Third-space fluid shift (physiological)",
      "Osmotic diuresis (physiological)",
      "Thermoregulatory sweating failure",
      "Circadian misalignment (shift work)",
      "Fever (physiological basis)"
    ],
    "lessCommon": [
      "Diabetes insipidus (physiological)",
      "SIADH (physiological)",
      "Decompression sickness",
      "Chronic mountain sickness",
      "Ondine's curse (central hypoventilation)",
      "Familial periodic paralysis",
      "Malignant hyperthermia",
      "Reflex sympathetic dystrophy",
      "Postural orthostatic tachycardia syndrome (POTS)",
      "Exercise-induced bronchospasm",
      "Renal tubular acidosis (physiological)",
      "Bartter syndrome (physiological)",
      "Gitelman syndrome (physiological)",
      "Cheyne-Stokes breathing",
      "Baroreceptor reflex failure",
      "Autonomic dysreflexia",
      "Cold agglutinin physiology",
      "Heat stroke (physiological failure)",
      "High-altitude pulmonary edema",
      "High-altitude cerebral edema",
      "Familial glucocorticoid deficiency",
      "Nephrogenic diabetes insipidus (physiological)",
      "Central diabetes insipidus (physiological)",
      "Cystic fibrosis-related sweat gland physiology",
      "Hypothermia (physiological cascade)",
      "Hyperthermia malignant susceptibility trait",
      "Vasovagal reflex hypersensitivity (carotid sinus syndrome)",
      "Autonomic failure (pure)",
      "Multiple system atrophy (autonomic physiology)",
      "Diabetic autonomic neuropathy (physiological)",
      "Sick sinus syndrome (physiological)",
      "Respiratory alkalosis (chronic)",
      "Hungry bone syndrome (physiological)",
      "Refeeding syndrome (physiological)",
      "Tumor lysis syndrome (physiological)",
      "Milk-alkali syndrome (physiological)",
      "Water intoxication (physiological)",
      "Salt-wasting nephropathy (physiological)",
      "Cerebral salt wasting syndrome",
      "Exercise-induced anaphylaxis"
    ],
    "rare": [
      "Congenital insensitivity to pain",
      "Guillain-Barré related autonomic dysfunction",
      "Central pontine myelinolysis (physiological correlate)",
      "Batten disease (metabolic/physiological)",
      "Familial dysautonomia (Riley-Day syndrome)",
      "Andersen-Tawil syndrome",
      "Brugada syndrome (channelopathy)",
      "Long QT syndrome",
      "Catecholaminergic polymorphic VT",
      "Primary hyperaldosteronism (physiological)",
      "Liddle syndrome",
      "Pseudohypoaldosteronism",
      "Congenital central hypoventilation syndrome",
      "Periodic fever syndromes (physiological basis)",
      "Familial hemiplegic migraine (channelopathy)",
      "Episodic ataxia (channelopathy)",
      "Timothy syndrome",
      "Short QT syndrome",
      "Hyperekplexia",
      "Paramyotonia congenita",
      "Malignant hyperthermia susceptibility (genetic)",
      "Stiff person syndrome",
      "Isaacs syndrome (neuromyotonia)",
      "Familial cold autoinflammatory syndrome",
      "Muckle-Wells syndrome",
      "CAPS (cryopyrin-associated periodic syndromes)",
      "Hyper-IgD syndrome",
      "TRAPS (TNF receptor-associated periodic syndrome)",
      "Congenital myasthenic syndrome",
      "Barth syndrome (physiological)",
      "Leigh syndrome (physiological)",
      "MELAS syndrome (physiological)",
      "MERRF syndrome (physiological)",
      "Kearns-Sayre syndrome (physiological)",
      "Pendred syndrome (physiological)",
      "Jervell and Lange-Nielsen syndrome",
      "Romano-Ward syndrome",
      "Anderson-Fabry disease (physiological)",
      "Congenital myotonia (Thomsen disease)",
      "Hyperinsulinism-hyperammonemia syndrome"
    ]
  },
  "Biochemistry": {
    "common": [
      "Diabetes mellitus (Type 1 & 2)",
      "Obesity/dyslipidemia",
      "Vitamin D deficiency (rickets/osteomalacia)",
      "Iron deficiency anemia",
      "Vitamin B12 deficiency",
      "Gout (hyperuricemia)",
      "Hypothyroidism (biochemical basis)",
      "Metabolic syndrome",
      "Fatty liver disease",
      "Protein-energy malnutrition (Kwashiorkor/Marasmus)",
      "Vitamin C deficiency (scurvy)",
      "Vitamin A deficiency (biochemical)",
      "Folate deficiency",
      "Vitamin B1 deficiency (beriberi)",
      "Vitamin B3 deficiency (pellagra)",
      "Zinc deficiency",
      "Hypercalcemia (biochemical basis)",
      "Hypocalcemia (biochemical basis)",
      "Hyperphosphatemia",
      "Hypomagnesemia",
      "Hyperuricemia (asymptomatic)",
      "Hypernatremia",
      "Hyponatremia (biochemical)",
      "Hyperkalemia (biochemical)",
      "Hypokalemia (biochemical)",
      "Hypervitaminosis A",
      "Hypervitaminosis D",
      "Vitamin E deficiency",
      "Vitamin K deficiency",
      "Copper deficiency",
      "Selenium deficiency",
      "Chromium deficiency",
      "Essential fatty acid deficiency",
      "Hyperlipoproteinemia (biochemical classification)",
      "Hypoproteinemia",
      "Hyperammonemia (biochemical)",
      "Lactic acidosis (biochemical)",
      "Ketoacidosis (biochemical)",
      "Hyperbilirubinemia (biochemical classification)",
      "Hypoalbuminemia"
    ],
    "lessCommon": [
      "G6PD deficiency",
      "Phenylketonuria (PKU)",
      "Galactosemia",
      "Wilson's disease",
      "Hemochromatosis",
      "Lactose intolerance",
      "Homocystinuria",
      "Maple syrup urine disease",
      "Glycogen storage diseases (von Gierke's, Pompe's)",
      "Familial hypercholesterolemia",
      "Alpha-1 antitrypsin deficiency",
      "Cystinuria",
      "Tyrosinemia",
      "Fructose intolerance (hereditary)",
      "Ornithine transcarbamylase deficiency",
      "Biotinidase deficiency",
      "Carnitine deficiency",
      "Medium-chain acyl-CoA dehydrogenase deficiency",
      "Abetalipoproteinemia",
      "Tangier disease",
      "Argininosuccinic aciduria",
      "Isovaleric acidemia",
      "Propionic acidemia",
      "Methylmalonic acidemia",
      "Glutaric aciduria type 1",
      "3-methylcrotonyl-CoA carboxylase deficiency",
      "Biotin-thiamine-responsive basal ganglia disease",
      "Hyperlysinemia",
      "Hyperprolinemia",
      "Sarcosinemia",
      "Alpha-mannosidosis",
      "Beta-mannosidosis",
      "Fucosidosis",
      "Sialidosis",
      "Mucolipidosis type IV",
      "Aspartylglucosaminuria",
      "GM1 gangliosidosis",
      "Wolman disease",
      "Cholesteryl ester storage disease",
      "Pyruvate dehydrogenase deficiency"
    ],
    "rare": [
      "Tay-Sachs disease",
      "Niemann-Pick disease",
      "Gaucher's disease",
      "Lesch-Nyhan syndrome",
      "Alkaptonuria",
      "Porphyrias (acute intermittent porphyria)",
      "Fabry disease",
      "Hurler syndrome (mucopolysaccharidosis)",
      "Zellweger syndrome",
      "Citrullinemia / urea cycle disorders",
      "Krabbe disease",
      "Metachromatic leukodystrophy",
      "Refsum disease",
      "Sandhoff disease",
      "Pompe disease (infantile)",
      "Menkes disease",
      "I-cell disease",
      "Congenital erythropoietic porphyria",
      "Farber disease",
      "Mucolipidosis",
      "Canavan disease",
      "Alexander disease",
      "Pelizaeus-Merzbacher disease",
      "Adrenoleukodystrophy",
      "Neuronal ceroid lipofuscinosis",
      "Sialic acid storage disease",
      "Danon disease",
      "CDG syndrome (congenital disorder of glycosylation)",
      "Multiple sulfatase deficiency",
      "Cerebrotendinous xanthomatosis",
      "Smith-Lemli-Opitz syndrome",
      "Peroxisomal biogenesis disorder",
      "Very long-chain acyl-CoA dehydrogenase deficiency",
      "Glutaric aciduria type 2",
      "Holocarboxylase synthetase deficiency",
      "Molybdenum cofactor deficiency",
      "Sulfite oxidase deficiency",
      "Hartnup disease",
      "Blue diaper syndrome",
      "Trimethylaminuria (fish odor syndrome)"
    ]
  },
  "Pathology": {
    "common": [
      "Atherosclerosis",
      "Tuberculosis (pathology)",
      "Ischemic heart disease / myocardial infarction",
      "Chronic inflammation-related fibrosis",
      "Iron deficiency anemia (pathology)",
      "Rheumatic heart disease",
      "Cirrhosis of liver",
      "Chronic kidney disease",
      "Benign prostatic hyperplasia",
      "Common carcinomas (breast, lung, cervix, oral)",
      "Acute pancreatitis (pathology)",
      "Peptic ulcer disease (pathology)",
      "Pulmonary embolism (pathology)",
      "Deep vein thrombosis (pathology)",
      "Chronic gastritis",
      "Fatty liver disease (pathology)",
      "Osteoarthritis (pathology)",
      "Chronic bronchitis (pathology)",
      "Emphysema (pathology)",
      "Colorectal polyps",
      "Chronic cholecystitis",
      "Peptic ulcer-associated gastritis",
      "Reflux esophagitis",
      "Barrett's esophagus",
      "Colonic diverticulosis",
      "Diverticulitis (pathology)",
      "Renal calculi (pathology)",
      "Prostatitis (pathology)",
      "Endometrial hyperplasia",
      "Uterine leiomyoma (pathology)",
      "Thyroiditis (Hashimoto's)",
      "Fibroadenoma of breast",
      "Lipoma (pathology)",
      "Squamous cell carcinoma (skin)",
      "Basal cell carcinoma",
      "Papillary thyroid carcinoma",
      "Adenomatous polyp",
      "Hyperplastic polyp",
      "Chronic pyelonephritis",
      "Acute tubular necrosis"
    ],
    "lessCommon": [
      "Amyloidosis",
      "Sarcoidosis",
      "Systemic lupus erythematosus",
      "Hodgkin's and Non-Hodgkin's lymphoma",
      "Multiple myeloma",
      "Wegener's granulomatosis (GPA)",
      "Polyarteritis nodosa",
      "Hemolytic anemias (autoimmune, hereditary spherocytosis)",
      "Nephrotic syndrome (minimal change, FSGS, membranous)",
      "Leukemias (acute and chronic)",
      "IgA nephropathy",
      "Membranoproliferative glomerulonephritis",
      "Myelodysplastic syndrome",
      "Polycythemia vera",
      "Essential thrombocythemia",
      "Primary myelofibrosis",
      "Giant cell arteritis",
      "Takayasu arteritis",
      "Churg-Strauss syndrome (EGPA)",
      "Sjögren's syndrome",
      "Membranous nephropathy",
      "Focal segmental glomerulosclerosis",
      "Diabetic nephropathy (pathology)",
      "Lupus nephritis",
      "Renal amyloidosis",
      "Interstitial nephritis (pathology)",
      "Alport syndrome (pathology)",
      "Thin basement membrane disease",
      "Chronic active hepatitis",
      "Non-alcoholic steatohepatitis",
      "Primary sclerosing cholangitis",
      "Autoimmune pancreatitis",
      "Chronic pancreatitis (pathology)",
      "Barrett's esophagus with dysplasia",
      "Gastric MALT lymphoma",
      "Celiac disease (pathology)",
      "Whipple's disease (pathology)",
      "Collagenous colitis",
      "Lymphocytic colitis",
      "Eosinophilic esophagitis"
    ],
    "rare": [
      "Langerhans cell histiocytosis",
      "Goodpasture syndrome",
      "Thrombotic thrombocytopenic purpura",
      "Castleman disease",
      "Mycosis fungoides",
      "Kaposi sarcoma",
      "Ewing's sarcoma",
      "Retinoblastoma",
      "Wilms tumor",
      "Burkitt lymphoma",
      "Angioimmunoblastic T-cell lymphoma",
      "Waldenström macroglobulinemia",
      "POEMS syndrome",
      "Erdheim-Chester disease",
      "Hemophagocytic lymphohistiocytosis",
      "Rosai-Dorfman disease",
      "Systemic mastocytosis",
      "Amyloid light-chain (AL) amyloidosis",
      "Familial Mediterranean fever (pathology)",
      "Behçet's disease (pathology)",
      "Inflammatory myofibroblastic tumor",
      "Solitary fibrous tumor",
      "Dermatofibrosarcoma protuberans",
      "Malignant peripheral nerve sheath tumor",
      "Alveolar soft part sarcoma",
      "Clear cell sarcoma",
      "Epithelioid hemangioendothelioma",
      "Pleuropulmonary blastoma",
      "Desmoplastic small round cell tumor",
      "Extraskeletal myxoid chondrosarcoma",
      "Follicular dendritic cell sarcoma",
      "Interdigitating dendritic cell sarcoma",
      "Blastic plasmacytoid dendritic cell neoplasm",
      "Intravascular large B-cell lymphoma",
      "Primary effusion lymphoma",
      "Plasmablastic lymphoma",
      "Composite lymphoma",
      "Sclerosing mesenteritis",
      "IgG4-related disease",
      "Multicentric Castleman disease"
    ]
  },
  "Pharmacology": {
    "common": [
      "Hypertension (drug therapy contexts)",
      "Type 2 diabetes (drug therapy)",
      "Peptic ulcer disease (drug-induced/treated)",
      "Bronchial asthma (pharmacotherapy)",
      "Bacterial infections (antibiotic contexts)",
      "Pain management contexts (NSAID use)",
      "Depression (antidepressant pharmacology)",
      "Epilepsy (antiepileptic pharmacology)",
      "Allergic rhinitis / anaphylaxis",
      "Drug-induced peptic ulcer/gastritis",
      "Hyperlipidemia (statin pharmacotherapy)",
      "Congestive heart failure (drug therapy)",
      "Arrhythmias (antiarrhythmic pharmacology)",
      "Tuberculosis (drug therapy)",
      "Anxiety disorders (anxiolytic pharmacology)",
      "Nausea/vomiting (antiemetic pharmacology)",
      "Constipation (laxative pharmacology)",
      "Hypothyroidism (drug therapy)",
      "Osteoporosis (drug therapy)",
      "Glaucoma (drug therapy)",
      "Peripheral neuropathy (drug-related)",
      "Diuretic-induced electrolyte imbalance",
      "Corticosteroid-induced osteoporosis",
      "Opioid-induced constipation",
      "Beta-blocker-induced bradycardia",
      "Calcium channel blocker-induced edema",
      "ACE inhibitor-induced cough",
      "Insulin-induced hypoglycemia",
      "Sulfonylurea-induced hypoglycemia",
      "Metformin-induced lactic acidosis",
      "Antihistamine-induced sedation",
      "Antipsychotic-induced weight gain",
      "Antidepressant discontinuation syndrome",
      "Benzodiazepine dependence",
      "Laxative abuse-related electrolyte imbalance",
      "Local anesthetic toxicity",
      "NSAID-induced gastritis",
      "Aspirin-induced bronchospasm",
      "Proton pump inhibitor-related deficiency (B12/Mg)",
      "Antibiotic-associated diarrhea"
    ],
    "lessCommon": [
      "Drug-induced hepatotoxicity",
      "Steroid-induced Cushing's syndrome",
      "Digoxin toxicity",
      "Warfarin-induced bleeding/skin necrosis",
      "Serotonin syndrome",
      "Neuroleptic malignant syndrome",
      "Aminoglycoside-induced ototoxicity/nephrotoxicity",
      "Methotrexate toxicity",
      "Drug-induced lupus",
      "Stevens-Johnson syndrome / TEN (drug-induced)",
      "Drug-induced pancreatitis",
      "ACE inhibitor-induced angioedema",
      "Beta-blocker-induced bronchospasm",
      "Statin-induced myopathy/rhabdomyolysis",
      "Heparin-induced thrombocytopenia",
      "Tardive dyskinesia (antipsychotic-induced)",
      "NSAID-induced nephropathy",
      "Tetracycline-induced dental staining/photosensitivity",
      "Fluoroquinolone-induced tendinopathy",
      "Valproate-induced hepatotoxicity",
      "Drug-induced parkinsonism",
      "Drug-induced gynecomastia",
      "Drug-induced hirsutism",
      "Isotretinoin-induced teratogenicity",
      "ACE inhibitor-induced hyperkalemia",
      "Thiazide-induced hyponatremia",
      "Loop diuretic-induced ototoxicity",
      "Antipsychotic-induced QT prolongation",
      "Antimalarial-induced retinopathy (chloroquine)",
      "Ethambutol-induced optic neuritis",
      "Linezolid-induced serotonin syndrome",
      "Metronidazole-induced peripheral neuropathy",
      "Nitrofurantoin-induced pulmonary fibrosis",
      "Sulfa drug-induced hypersensitivity",
      "Phenytoin-induced gingival hyperplasia",
      "Carbamazepine-induced hyponatremia",
      "Lamotrigine-induced Stevens-Johnson syndrome",
      "Beta-lactam-induced interstitial nephritis",
      "Rifampicin-induced hepatotoxicity",
      "Pyrazinamide-induced hyperuricemia"
    ],
    "rare": [
      "Chloramphenicol-induced aplastic anemia / gray baby syndrome",
      "Thalidomide-induced phocomelia",
      "Reye's syndrome (aspirin-associated)",
      "Halothane hepatitis",
      "Isoniazid-induced peripheral neuropathy",
      "Fixed drug eruption (severe forms)",
      "Lithium-induced nephrogenic diabetes insipidus",
      "Malignant hyperthermia (anesthetic drugs)",
      "Ergotism",
      "Black cohosh/herbal drug-induced hepatotoxicity",
      "Amiodarone-induced pulmonary fibrosis",
      "Amiodarone-induced thyroid dysfunction",
      "Bleomycin-induced pulmonary fibrosis",
      "Cisplatin-induced nephrotoxicity/ototoxicity",
      "Vancomycin-induced red man syndrome",
      "Clozapine-induced agranulocytosis",
      "Methemoglobinemia (drug-induced)",
      "Cocaine-induced cardiac ischemia (toxicological)",
      "Digitalis-induced xanthopsia",
      "Propylthiouracil-induced hepatotoxicity",
      "Fibrosing drug reaction (ergot-related valvulopathy)",
      "Gadolinium-induced nephrogenic systemic fibrosis",
      "Radiocontrast-induced thyrotoxicosis",
      "Levamisole-induced vasculitis",
      "Hydralazine-induced ANCA vasculitis",
      "Propylthiouracil-induced ANCA vasculitis",
      "Minocycline-induced hyperpigmentation",
      "Gold salt-induced nephropathy",
      "D-penicillamine-induced myasthenia",
      "Bromocriptine-induced valvulopathy",
      "Pergolide-induced valvulopathy",
      "Fenfluramine-induced valvulopathy",
      "Interferon-induced autoimmune disease",
      "Checkpoint inhibitor-induced colitis",
      "Checkpoint inhibitor-induced pneumonitis",
      "Tyrosine kinase inhibitor-induced cardiotoxicity",
      "Anthracycline-induced cardiomyopathy",
      "Trastuzumab-induced cardiotoxicity",
      "5-fluorouracil-induced cardiotoxicity",
      "Bortezomib-induced peripheral neuropathy"
    ]
  },
  "Microbiology": {
    "common": [
      "Tuberculosis",
      "Typhoid fever",
      "Urinary tract infection (E. coli)",
      "Streptococcal pharyngitis",
      "Staphylococcal skin infections",
      "Malaria",
      "Dengue fever",
      "Viral hepatitis (A, B, C)",
      "HIV/AIDS",
      "Fungal skin infections (dermatophytosis, candidiasis)",
      "Cholera",
      "Chickenpox (Varicella)",
      "Measles",
      "Mumps",
      "Rubella",
      "Herpes simplex infection",
      "Influenza",
      "Pneumococcal pneumonia",
      "Whooping cough (Pertussis)",
      "Salmonellosis",
      "Bacterial vaginosis (microbiology)",
      "Otitis media (bacterial)",
      "Impetigo (bacterial)",
      "Cellulitis (bacterial)",
      "Conjunctivitis (bacterial)",
      "Gonorrhea",
      "Chlamydial infection",
      "Trichomoniasis",
      "Herpes labialis",
      "Molluscum contagiosum (viral)",
      "Roseola infantum",
      "Erythema infectiosum (fifth disease)",
      "Hand, foot, and mouth disease (viral)",
      "Common wart (HPV)",
      "Genital wart (HPV)",
      "Tinea capitis",
      "Tinea corporis",
      "Oral candidiasis (thrush)",
      "Bacterial food poisoning (Staph aureus toxin)",
      "Shigellosis"
    ],
    "lessCommon": [
      "Leptospirosis",
      "Brucellosis",
      "Diphtheria",
      "Pertussis (whooping cough)",
      "Tetanus",
      "Rabies",
      "Amoebiasis",
      "Giardiasis",
      "Cryptococcal meningitis",
      "Mucormycosis",
      "Toxoplasmosis",
      "Cytomegalovirus infection",
      "Epstein-Barr virus infection (infectious mononucleosis)",
      "Listeriosis",
      "Scrub typhus",
      "Q fever",
      "Aspergillosis",
      "Blastomycosis",
      "Coccidioidomycosis",
      "Cysticercosis",
      "Yersiniosis",
      "Campylobacteriosis",
      "Vibrio parahaemolyticus infection",
      "Clostridioides difficile infection",
      "Legionellosis",
      "Psittacosis",
      "Bartonellosis (cat scratch disease)",
      "Tularemia (lessCommon variant)",
      "Erysipelothrix infection",
      "Nocardiosis",
      "Sporotrichosis",
      "Chromoblastomycosis",
      "Paracoccidioidomycosis",
      "Strongyloidiasis",
      "Ascariasis",
      "Hookworm infection",
      "Trichuriasis",
      "Enterobiasis (pinworm)",
      "Schistosomiasis",
      "Filariasis (Wuchereria bancrofti)"
    ],
    "rare": [
      "Anthrax",
      "Plague (Yersinia pestis)",
      "Melioidosis",
      "Nipah virus infection",
      "Kyasanur Forest disease",
      "Chikungunya (severe complications)",
      "Cholera (severe outbreak forms)",
      "Actinomycosis",
      "Histoplasmosis",
      "Prion diseases (Creutzfeldt-Jakob disease)",
      "Ebola virus disease",
      "Marburg virus disease",
      "Lassa fever",
      "Botulism",
      "Diphtheria (severe systemic complications)",
      "Tularemia",
      "Whipple's disease",
      "Progressive multifocal leukoencephalopathy",
      "Human African trypanosomiasis",
      "Rat-bite fever",
      "Whipple's disease (microbiology)",
      "Human granulocytic anaplasmosis",
      "Ehrlichiosis",
      "Relapsing fever (Borrelia)",
      "Bejel (endemic syphilis)",
      "Pinta",
      "Glanders",
      "Rat-bite fever (Spirillum)",
      "Vibrio vulnificus necrotizing infection",
      "Chromomycosis (severe)",
      "Mycetoma",
      "Loa loa infection (loiasis)",
      "Onchocerciasis (microbiology)",
      "Dracunculiasis (microbiology)",
      "Paragonimiasis",
      "Fascioliasis",
      "Clonorchiasis",
      "Trichinellosis",
      "Angiostrongyliasis",
      "Baylisascariasis"
    ]
  },
  "Forensic Medicine & Toxicology": {
    "common": [
      "Organophosphate poisoning",
      "Alcohol intoxication/dependence",
      "Road traffic accident-related injuries",
      "Burns (medicolegal aspects)",
      "Snake bite (venomous)",
      "Corrosive/acid poisoning",
      "Firearm injuries (medicolegal)",
      "Drowning",
      "Hanging/asphyxial deaths",
      "Domestic violence-related injuries",
      "Blunt force trauma (medicolegal)",
      "Sharp force injuries (stab wounds)",
      "Suicide by poisoning (medicolegal)",
      "Food poisoning (medicolegal)",
      "Industrial accident injuries",
      "Child abuse-related injuries",
      "Strangulation (manual/ligature)",
      "Postmortem interval estimation cases",
      "Traffic fatality (pedestrian)",
      "Chemical burns (occupational)",
      "Fall from height (medicolegal)",
      "Assault-related soft tissue injury",
      "Bite mark injury (medicolegal)",
      "Fireworks-related injury",
      "Occupational crush injury",
      "Railway accident injury (medicolegal)",
      "Alcohol-related road traffic fatality",
      "Poisoning by household cleaning agents",
      "Accidental drug overdose (medicolegal)",
      "Fire-related smoke inhalation death",
      "Workplace fatality (industrial)",
      "Animal bite injury (medicolegal)",
      "Self-inflicted injury (non-fatal)",
      "Torture-related injury pattern",
      "Whiplash injury (medicolegal)",
      "Choking (foreign body, medicolegal)",
      "Elder abuse-related injury",
      "Occupational needle-stick exposure",
      "Assault with blunt weapon",
      "Injury from industrial machinery"
    ],
    "lessCommon": [
      "Barbiturate/benzodiazepine poisoning",
      "Opioid overdose",
      "Kerosene/hydrocarbon poisoning",
      "Rodenticide (zinc phosphide) poisoning",
      "Carbon monoxide poisoning",
      "Electrocution injuries",
      "Heat stroke (medicolegal)",
      "Scorpion sting",
      "Aluminium phosphide poisoning",
      "Sexual assault-related injury patterns",
      "Copper sulfate poisoning",
      "Datura poisoning",
      "Insecticide (carbamate) poisoning",
      "Methanol poisoning",
      "Ethylene glycol poisoning",
      "Paraquat poisoning",
      "Cannabis intoxication (medicolegal)",
      "Amphetamine/stimulant toxicity",
      "Neonaticide/infant death investigation",
      "Occupational lead poisoning (forensic)",
      "Sodium fluoroacetate poisoning",
      "Endosulfan poisoning",
      "DDT/organochlorine poisoning",
      "Nicotine poisoning (medicolegal)",
      "Camphor poisoning",
      "Naphthalene poisoning",
      "Turpentine poisoning",
      "Phenol poisoning",
      "Formaldehyde exposure (forensic)",
      "Ethylene dibromide poisoning",
      "Cadmium poisoning (forensic)",
      "Chromium poisoning (occupational forensic)",
      "Benzene toxicity (occupational forensic)",
      "Toluene toxicity (occupational forensic)",
      "Chronic solvent abuse syndrome",
      "Anabolic steroid abuse (forensic)",
      "Body packer syndrome (drug smuggling)",
      "Custodial death investigation",
      "Autoerotic asphyxiation death",
      "Postmortem artifact misinterpretation cases"
    ],
    "rare": [
      "Arsenic poisoning (chronic)",
      "Lead poisoning (medicolegal)",
      "Mercury poisoning",
      "Thallium poisoning",
      "Cyanide poisoning",
      "Mushroom poisoning",
      "Puffer fish (tetrodotoxin) poisoning",
      "Radiation injury",
      "Munchausen syndrome by proxy",
      "Fetal death/infanticide medicolegal cases",
      "Ricin poisoning",
      "Strychnine poisoning",
      "Digitalis poisoning (forensic)",
      "Insulin homicide/overdose cases",
      "Air embolism (forensic)",
      "Spontaneous human combustion (forensic myth investigation)",
      "Sudden infant death syndrome (forensic)",
      "Excited delirium syndrome",
      "Battered baby syndrome",
      "Postmortem lividity anomaly cases",
      "Colchicine poisoning",
      "Digoxin homicide cases",
      "Warfarin homicide/poisoning cases",
      "Barium carbonate poisoning",
      "Selenium poisoning",
      "Antimony poisoning",
      "Botulinum toxin poisoning (non-therapeutic)",
      "Nerve agent exposure (forensic)",
      "Mustard gas exposure (forensic)",
      "Polonium poisoning",
      "Chemical warfare agent exposure",
      "Fentanyl analog mass poisoning",
      "Serial poisoning case patterns",
      "Sudden unexplained death in epilepsy (forensic)",
      "Excited delirium-associated custody death",
      "Cot death (forensic SIDS workup)",
      "Anaphylactic death (forensic)",
      "Vagal inhibition death",
      "Traumatic asphyxia (crowd crush)",
      "Decomposition-altered injury interpretation"
    ]
  },
  "Community Medicine": {
    "common": [
      "Malnutrition (PEM, stunting, wasting)",
      "Anemia (public health burden)",
      "Diarrheal diseases (childhood)",
      "Acute respiratory infections (childhood)",
      "Tuberculosis (public health)",
      "Vaccine-preventable diseases (measles, polio)",
      "Hypertension (population screening)",
      "Diabetes (population screening)",
      "Maternal mortality-related conditions",
      "Vector-borne diseases (malaria, dengue, filariasis)",
      "Obesity (public health)",
      "Cardiovascular disease (population burden)",
      "Cervical cancer (screening programs)",
      "Breast cancer (screening programs)",
      "Neonatal mortality-related conditions",
      "Adolescent reproductive health issues",
      "Tobacco use-related disease burden",
      "Alcohol use disorder (public health)",
      "Road traffic injury (public health)",
      "Mental health disorders (community burden)",
      "Childhood obesity (public health)",
      "Anemia in adolescent girls (public health)",
      "Low birth weight (public health)",
      "Exclusive breastfeeding gaps (public health)",
      "Immunization dropout (public health)",
      "Open defecation-related disease burden",
      "Indoor air pollution-related illness",
      "Unsafe drinking water-related disease",
      "Occupational back pain (public health)",
      "Non-communicable disease risk factor clustering",
      "Hypertension in the elderly (community)",
      "Diabetic foot complications (community screening)",
      "Cataract blindness (community burden)",
      "Refractive error in school children (screening)",
      "Dental caries (community burden)",
      "Malnutrition in under-5 children",
      "Teenage pregnancy-related morbidity",
      "Domestic violence-related morbidity (public health)",
      "Substance abuse among youth (public health)",
      "Suicide risk in community (public health surveillance)"
    ],
    "lessCommon": [
      "Iodine deficiency disorders (goiter)",
      "Vitamin A deficiency (xerophthalmia)",
      "Occupational lung diseases (silicosis, byssinosis)",
      "Fluorosis",
      "Leprosy (public health control)",
      "HIV/AIDS (epidemiological)",
      "Lymphatic filariasis",
      "Japanese encephalitis",
      "Rabies (public health control)",
      "Tobacco-related diseases (population level)",
      "Waterborne disease outbreaks (community)",
      "Noise-induced hearing loss (occupational)",
      "Pesticide exposure-related illness (agricultural)",
      "Anemia in pregnancy (public health)",
      "Zoonotic disease surveillance conditions",
      "Air pollution-related respiratory disease",
      "Sickle cell disease (community screening)",
      "Thalassemia (community screening)",
      "Hepatitis B (immunization programs)",
      "Chikungunya outbreaks (community)",
      "Silicosis (occupational cohort surveillance)",
      "Byssinosis (occupational cohort)",
      "Asbestosis (occupational)",
      "Farmer's lung (hypersensitivity pneumonitis)",
      "Coal workers' pneumoconiosis",
      "Heat-related illness in outdoor workers",
      "Manual scavenging-related disease",
      "Migrant worker health burden",
      "Urban slum-related disease clustering",
      "Refugee/displaced population disease burden",
      "Zoonotic influenza surveillance",
      "Avian influenza outbreak (public health)",
      "MERS-CoV surveillance (public health)",
      "Antimicrobial resistance surveillance burden",
      "Healthcare-associated infection surveillance",
      "Snakebite burden (rural public health)",
      "Dog bite/rabies exposure burden",
      "Occupational asthma (public health)",
      "Noise pollution-related hypertension (community)",
      "Heavy metal contamination-related illness (community)"
    ],
    "rare": [
      "Guinea worm disease (dracunculiasis) — near eradicated",
      "Yaws",
      "Trachoma (blinding)",
      "Kala-azar (visceral leishmaniasis)",
      "Cholera outbreaks",
      "Nipah virus outbreaks",
      "Anthrax (occupational/zoonotic)",
      "Radiation exposure disorders",
      "Endemic fluorosis-related skeletal deformity",
      "Minamata disease (mercury, environmental)",
      "Itai-itai disease (cadmium poisoning)",
      "Bhopal gas tragedy-related illness (methyl isocyanate exposure)",
      "Podoconiosis",
      "Buruli ulcer",
      "Congenital rubella syndrome (eradication surveillance)",
      "Neonatal tetanus (elimination surveillance)",
      "Diphtheria resurgence (public health)",
      "Lathyrism",
      "Endemic goiter cretinism",
      "Onchocerciasis (river blindness)",
      "Congenital Zika syndrome (surveillance)",
      "Monkeypox (mpox) outbreak (public health)",
      "Avian influenza H5N1 human case (public health)",
      "Nipah virus spillover event (surveillance)",
      "Anthrax outbreak (zoonotic, community)",
      "Guinea worm resurgence case (surveillance)",
      "Vaccine-derived poliovirus case (surveillance)",
      "Diphtheria outbreak (resurgent, community)",
      "Circulating vaccine-derived poliovirus outbreak",
      "Cholera pandemic strain outbreak",
      "Plague outbreak (sylvatic, community)",
      "Rift Valley fever outbreak",
      "Crimean-Congo hemorrhagic fever outbreak",
      "West Nile virus outbreak (community)",
      "Zika virus outbreak (community)",
      "Yellow fever outbreak (community)",
      "Lassa fever outbreak (community)",
      "Marburg virus outbreak (community)",
      "Ebola virus outbreak (community)",
      "Radiation disaster-related illness (community, e.g. Chernobyl-type)"
    ]
  },
  "Ophthalmology": {
    "common": [
      "Refractive errors (myopia, hypermetropia, astigmatism)",
      "Cataract",
      "Conjunctivitis (bacterial/viral/allergic)",
      "Diabetic retinopathy",
      "Trachoma",
      "Stye (hordeolum)",
      "Dry eye disease",
      "Pterygium",
      "Corneal abrasion/foreign body",
      "Chalazion",
      "Blepharitis",
      "Subconjunctival hemorrhage",
      "Presbyopia",
      "Amblyopia",
      "Entropion/ectropion",
      "Dacryocystitis",
      "Episcleritis",
      "Xerophthalmia (ophthalmic)",
      "Hypertensive retinopathy (mild)",
      "Allergic conjunctivitis (vernal)",
      "Meibomian gland dysfunction",
      "Floppy eyelid syndrome",
      "Ectropion (involutional)",
      "Entropion (involutional)",
      "Corneal foreign body (metallic)",
      "Photokeratitis (welder's flash)",
      "Allergic conjunctivitis (seasonal)",
      "Bacterial keratitis (mild)",
      "Ocular surface disease (dry eye related)",
      "Blepharospasm (benign essential)",
      "Ptosis (age-related)",
      "Epiphora (watering eye)",
      "Chronic dacryocystitis",
      "Conjunctival cyst",
      "Pinguecula",
      "Convergence insufficiency",
      "Accommodative esotropia",
      "Anisometropia",
      "Color vision deficiency",
      "Night blindness (nutritional)"
    ],
    "lessCommon": [
      "Glaucoma (primary open angle, angle closure)",
      "Uveitis",
      "Retinal detachment",
      "Central retinal artery/vein occlusion",
      "Squint (strabismus)",
      "Keratoconus",
      "Optic neuritis",
      "Corneal ulcer (bacterial/fungal)",
      "Endophthalmitis",
      "Hypertensive retinopathy",
      "Age-related macular degeneration",
      "Diabetic macular edema",
      "Herpes zoster ophthalmicus",
      "Scleritis",
      "Orbital cellulitis",
      "Thyroid eye disease (Graves' ophthalmopathy)",
      "Nystagmus (acquired)",
      "Retinal vein occlusion (branch)",
      "Vitreous hemorrhage",
      "Papilledema",
      "Fuchs heterochromic iridocyclitis",
      "Posner-Schlossman syndrome",
      "Iridocorneal endothelial syndrome",
      "Peters anomaly",
      "Axenfeld-Rieger syndrome",
      "Aniridia",
      "Coloboma (ocular)",
      "Persistent hyperplastic primary vitreous",
      "Retinopathy of prematurity",
      "Toxoplasma retinochoroiditis",
      "Cytomegalovirus retinitis",
      "Ocular toxocariasis",
      "Branch retinal artery occlusion",
      "Central serous chorioretinopathy",
      "Macular hole",
      "Epiretinal membrane",
      "Vitreomacular traction syndrome",
      "Ocular myasthenia gravis",
      "Thyroid-associated orbitopathy (severe)",
      "Orbital pseudotumor"
    ],
    "rare": [
      "Retinoblastoma",
      "Retinitis pigmentosa",
      "Sympathetic ophthalmia",
      "Orbital cellulitis (severe complications)",
      "Congenital glaucoma (buphthalmos)",
      "Marfan syndrome-related lens dislocation",
      "Coats disease",
      "Choroidal melanoma",
      "Fuchs' endothelial dystrophy",
      "Behçet's disease (ocular involvement)",
      "Leber's hereditary optic neuropathy",
      "Optic nerve glioma",
      "Persistent fetal vasculature",
      "Uveal melanoma (advanced)",
      "Acanthamoeba keratitis",
      "Sympathetic uveitis (post-traumatic)",
      "Vogt-Koyanagi-Harada disease",
      "Best disease (vitelliform dystrophy)",
      "Congenital rubella cataract syndrome",
      "Anophthalmia/microphthalmia",
      "Norrie disease",
      "Leber congenital amaurosis",
      "Stargardt disease",
      "Choroideremia",
      "Gyrate atrophy of choroid and retina",
      "Bietti crystalline dystrophy",
      "Familial exudative vitreoretinopathy",
      "Incontinentia pigmenti (ocular)",
      "Peters plus syndrome",
      "WAGR syndrome (ocular)",
      "Sturge-Weber syndrome (ocular)",
      "Neurofibromatosis (ocular manifestations)",
      "Von Hippel-Lindau disease (ocular)",
      "Tuberous sclerosis (ocular)",
      "Wyburn-Mason syndrome",
      "Orbital rhabdomyosarcoma",
      "Adenoid cystic carcinoma of lacrimal gland",
      "Optic pathway glioma",
      "Ocular ischemic syndrome",
      "Terson syndrome"
    ]
  },
  "Otorhinolaryngology (ENT)": {
    "common": [
      "Otitis media (acute/chronic)",
      "Sinusitis",
      "Tonsillitis/pharyngitis",
      "Allergic rhinitis",
      "Epistaxis",
      "Deviated nasal septum",
      "Wax impaction (cerumen)",
      "Foreign body in ear/nose",
      "Hearing loss (conductive/sensorineural, age-related)",
      "Laryngitis",
      "Otitis externa",
      "Common cold (upper respiratory infection)",
      "Adenoiditis",
      "Nasal furuncle",
      "Snoring/obstructive sleep apnea (ENT)",
      "Tinnitus",
      "Perforated tympanic membrane (traumatic)",
      "Acute pharyngitis (viral)",
      "Salivary gland calculi (sialolithiasis)",
      "Chronic rhinosinusitis",
      "Barotrauma of ear",
      "Impacted tooth-related sinus infection",
      "Eustachian tube dysfunction",
      "Chronic tonsillar hypertrophy",
      "Nasal septal hematoma",
      "Nasal bone fracture",
      "Auricular hematoma",
      "Foreign body bronchus (ENT-adjacent)",
      "Globus pharyngeus",
      "Acute laryngotracheitis",
      "Recurrent tonsillitis (chronic)",
      "Deviated septum with turbinate hypertrophy",
      "Post-nasal drip syndrome",
      "Otomycosis",
      "Ear canal exostosis (surfer's ear)",
      "Traumatic tympanic membrane perforation",
      "Vocal strain/phonotrauma",
      "Chronic cough (ENT-related)",
      "Halitosis (ENT-related)",
      "Snoring (simple, non-apneic)"
    ],
    "lessCommon": [
      "Otosclerosis",
      "Ménière's disease",
      "Vocal cord nodules/polyps",
      "Nasal polyposis",
      "Peritonsillar abscess (quinsy)",
      "Mastoiditis",
      "Vestibular neuronitis",
      "Laryngeal papillomatosis",
      "Adenoid hypertrophy",
      "Sudden sensorineural hearing loss",
      "Retropharyngeal abscess",
      "Epiglottitis (acute)",
      "Ludwig's angina",
      "Parotitis (non-mumps)",
      "Cholesteatoma (uncomplicated)",
      "Laryngomalacia",
      "Vocal cord paralysis",
      "Bell's palsy (ENT correlation)",
      "Sialadenitis (chronic)",
      "Allergic fungal sinusitis",
      "Juvenile recurrent parotitis",
      "Sialorrhea (chronic)",
      "Frey syndrome",
      "Sistrunk-requiring thyroglossal duct cyst (ENT)",
      "Branchial cleft fistula (ENT)",
      "Laryngopharyngeal reflux",
      "Reinke's edema",
      "Contact granuloma of larynx",
      "Subglottic stenosis",
      "Tracheomalacia",
      "Choanal stenosis",
      "Nasal septal perforation",
      "Empty nose syndrome",
      "Atrophic rhinitis (ozena)",
      "Wegener's-related saddle nose deformity",
      "Relapsing polychondritis (ENT)",
      "Eagle syndrome (elongated styloid)",
      "First bite syndrome",
      "Superior laryngeal nerve palsy",
      "Globus hystericus with underlying pathology"
    ],
    "rare": [
      "Nasopharyngeal carcinoma",
      "Laryngeal carcinoma",
      "Acoustic neuroma",
      "Cholesteatoma (complicated)",
      "Juvenile angiofibroma",
      "Wegener's granulomatosis (ENT presentation)",
      "Ramsay Hunt syndrome",
      "Glomus jugulare tumor",
      "Rhinoscleroma",
      "Necrotizing (malignant) otitis externa",
      "Parapharyngeal space tumor",
      "Esthesioneuroblastoma",
      "Laryngeal amyloidosis",
      "Sinonasal undifferentiated carcinoma",
      "Cerebellopontine angle tumor (ENT presentation)",
      "Choanal atresia",
      "First branchial cleft anomaly",
      "Rhinocerebral mucormycosis",
      "Perilymph fistula",
      "Otic capsule otosclerosis (far advanced)",
      "Sinonasal inverted papilloma",
      "Olfactory neuroblastoma (advanced)",
      "Nasal NK/T-cell lymphoma",
      "Chordoma of skull base (ENT presentation)",
      "Fibrous dysplasia of skull base",
      "Osteoradionecrosis of mandible",
      "Malignant otitis externa (advanced)",
      "Petrous apicitis",
      "Lemierre syndrome",
      "Jugular foramen syndrome",
      "Vernet syndrome",
      "Villaret syndrome",
      "Collet-Sicard syndrome",
      "Tolosa-Hunt syndrome (ENT overlap)",
      "Kimura disease (ENT)",
      "Rosai-Dorfman disease (ENT)",
      "Sinonasal glomangiopericytoma",
      "Teratocarcinosarcoma (sinonasal)",
      "Congenital cholesteatoma",
      "Cochlear otosclerosis (far advanced)"
    ]
  },
  "General Medicine": {
    "common": [
      "Hypertension",
      "Type 2 diabetes mellitus",
      "Ischemic heart disease",
      "Chronic obstructive pulmonary disease (COPD)",
      "Bronchial asthma",
      "Community-acquired pneumonia",
      "Pulmonary tuberculosis",
      "Peptic ulcer disease / GERD",
      "Chronic kidney disease",
      "Anemia (iron deficiency)",
      "Urinary tract infection",
      "Viral hepatitis (acute)",
      "Dengue fever (uncomplicated)",
      "Typhoid fever (clinical)",
      "Hypothyroidism",
      "Hyperthyroidism (Graves' disease)",
      "Osteoarthritis (clinical)",
      "Gout (clinical)",
      "Migraine",
      "Depression (clinical presentation)",
      "Chronic constipation (clinical)",
      "Irritable bowel syndrome",
      "Gastritis (clinical)",
      "Cellulitis (clinical)",
      "Herpes zoster (clinical)",
      "Sinusitis (clinical)",
      "Allergic rhinitis (clinical)",
      "Obesity (clinical)",
      "Metabolic syndrome (clinical)",
      "Vitamin D deficiency (clinical)",
      "Osteoporosis (clinical)",
      "Insomnia (clinical)",
      "Tension headache",
      "Vertigo (peripheral)",
      "Chronic fatigue syndrome",
      "Fibromyalgia",
      "Restless legs syndrome",
      "Erectile dysfunction (clinical)",
      "Benign prostatic hyperplasia (clinical)",
      "Urinary incontinence"
    ],
    "lessCommon": [
      "Congestive heart failure",
      "Stroke (ischemic/hemorrhagic)",
      "Chronic liver disease/cirrhosis",
      "Rheumatoid arthritis",
      "Systemic lupus erythematosus",
      "Hypothyroidism/hyperthyroidism",
      "Nephrotic/nephritic syndrome",
      "Malaria (complicated)",
      "Dengue (with warning signs)",
      "Enteric (typhoid) fever with complications",
      "Infective endocarditis",
      "Pericarditis (acute)",
      "Deep vein thrombosis (clinical)",
      "Pulmonary embolism (clinical)",
      "Chronic pancreatitis",
      "Inflammatory bowel disease (Crohn's/UC)",
      "Vitamin B12 deficiency (clinical anemia)",
      "Sarcoidosis (clinical)",
      "Sjögren's syndrome (clinical)",
      "Polymyalgia rheumatica",
      "Chronic fatigue with autoimmune overlap",
      "Vasculitis (cutaneous, clinical)",
      "Reactive arthritis",
      "Psoriatic arthritis",
      "Gouty tophi with chronic disease",
      "Chronic hepatitis B/C (clinical)",
      "Alcoholic liver disease (clinical)",
      "Hemochromatosis with organ involvement",
      "Chronic pancreatitis (clinical)",
      "Celiac disease (clinical)",
      "Irritable bowel disease flare (clinical)",
      "Peripheral neuropathy (clinical, diabetic)",
      "Restrictive lung disease (clinical)",
      "Bronchiectasis (clinical)",
      "Pulmonary hypertension (clinical)",
      "Cor pulmonale",
      "Chronic anemia of chronic disease",
      "Hemolytic anemia (clinical, acquired)",
      "Aplastic anemia (clinical)",
      "Myelodysplastic syndrome (clinical)"
    ],
    "rare": [
      "HIV/AIDS with opportunistic infections",
      "Systemic sclerosis (scleroderma)",
      "Guillain-Barré syndrome",
      "Myasthenia gravis",
      "Addison's disease",
      "Pheochromocytoma",
      "Amyloidosis (systemic)",
      "Wilson's disease (clinical)",
      "Hemochromatosis (clinical)",
      "Thrombotic thrombocytopenic purpura",
      "Cushing's syndrome (endogenous)",
      "Acromegaly",
      "SIADH (clinical)",
      "Multiple sclerosis",
      "Systemic vasculitis (ANCA-associated)",
      "Primary biliary cholangitis",
      "Autoimmune hepatitis",
      "Whipple's disease (clinical)",
      "Familial Mediterranean fever (clinical)",
      "Paraneoplastic syndromes",
      "POEMS syndrome (clinical)",
      "Stiff person syndrome (clinical)",
      "Paraneoplastic cerebellar degeneration",
      "Limbic encephalitis (autoimmune)",
      "Anti-NMDA receptor encephalitis",
      "IgG4-related disease (clinical)",
      "Erdheim-Chester disease (clinical)",
      "Castleman disease (clinical)",
      "Relapsing polychondritis (clinical)",
      "Adult-onset Still's disease",
      "Eosinophilic granulomatosis with polyangiitis",
      "Cryoglobulinemic vasculitis",
      "Behçet's disease (clinical)",
      "Familial Mediterranean fever (systemic clinical)",
      "Fabry disease (clinical, adult)",
      "Gaucher disease (clinical, adult)",
      "Hereditary angioedema",
      "Alpha-1 antitrypsin deficiency (clinical, adult)",
      "Primary ciliary dyskinesia (clinical)",
      "Common variable immunodeficiency"
    ]
  },
  "General Surgery": {
    "common": [
      "Acute appendicitis",
      "Inguinal hernia",
      "Gallstone disease/cholecystitis",
      "Hemorrhoids",
      "Peptic ulcer perforation",
      "Breast lump (fibroadenoma/carcinoma workup)",
      "Thyroid nodule/goiter",
      "Intestinal obstruction",
      "Wound infections/abscess",
      "Varicose veins (surgical)",
      "Anal fissure",
      "Pilonidal sinus",
      "Lipoma (surgical excision)",
      "Sebaceous cyst",
      "Umbilical hernia (surgical)",
      "Femoral hernia",
      "Diabetic foot ulcer (surgical)",
      "Breast abscess",
      "Skin and soft tissue abscess",
      "Ganglion cyst",
      "Incisional hernia",
      "Epigastric hernia",
      "Spigelian hernia",
      "Sebaceous cyst infection",
      "Ingrown toenail (surgical)",
      "Boil/carbuncle",
      "Breast cyst (surgical evaluation)",
      "Gynecomastia (surgical)",
      "Thyroglossal duct cyst (surgical)",
      "Branchial cyst (surgical)",
      "Dermoid cyst (surgical)",
      "Ranula",
      "Sialolithiasis (surgical)",
      "Fistula-in-ano (simple)",
      "Rectal polyp (surgical)",
      "Anal warts (surgical)",
      "Varicocele",
      "Hydrocele (surgical)",
      "Epididymal cyst",
      "Sebaceous horn"
    ],
    "lessCommon": [
      "Acute pancreatitis",
      "Diabetic foot/gangrene",
      "Perianal fistula",
      "Peripheral arterial disease",
      "Carcinoma stomach",
      "Carcinoma colon/rectum",
      "Splenic injury/rupture",
      "Hydatid cyst (liver)",
      "Thyroid carcinoma",
      "Umbilical/incisional hernia",
      "Achalasia cardia",
      "Gastroesophageal reflux disease (surgical)",
      "Rectal prolapse",
      "Anal fistula (complex)",
      "Chronic pancreatitis (surgical)",
      "Choledochal cyst",
      "Carcinoma esophagus",
      "Carcinoma gallbladder",
      "Splenomegaly (surgical workup)",
      "Mesenteric ischemia",
      "Carcinoma pancreas (head, surgical)",
      "Carcinoma of ampulla of Vater",
      "Duodenal diverticulum",
      "Jejunal diverticulosis",
      "Meckel's diverticulum complications (surgical)",
      "Intestinal tuberculosis (surgical)",
      "Ileocecal tuberculosis",
      "Amoebic liver abscess (surgical)",
      "Pyogenic liver abscess",
      "Portal hypertension (surgical)",
      "Esophageal varices (surgical)",
      "Achalasia (advanced, surgical)",
      "Boerhaave syndrome (surgical repair context)",
      "Diaphragmatic hernia (adult, surgical)",
      "Splenic abscess",
      "Retroperitoneal abscess",
      "Psoas abscess",
      "Perinephric abscess",
      "Renal cell carcinoma (surgical)",
      "Adrenal incidentaloma"
    ],
    "rare": [
      "Carcinoid tumor",
      "Gastrointestinal stromal tumor (GIST)",
      "Pheochromocytoma (surgical)",
      "Retroperitoneal sarcoma",
      "Zollinger-Ellison syndrome",
      "Boerhaave syndrome (esophageal rupture)",
      "Meckel's diverticulitis",
      "Volvulus (sigmoid/cecal)",
      "Necrotizing fasciitis",
      "Pancreatic pseudocyst with complications",
      "Insulinoma",
      "Pancreatic carcinoma (advanced)",
      "Adrenal carcinoma",
      "Desmoid tumor",
      "Sistrunk-requiring thyroglossal fistula",
      "Mirizzi syndrome",
      "Klatskin tumor (cholangiocarcinoma)",
      "Fournier's gangrene",
      "Ogilvie syndrome (colonic pseudo-obstruction)",
      "Peutz-Jeghers syndrome (surgical)",
      "Pseudomyxoma peritonei",
      "Mesenteric cyst",
      "Omental torsion",
      "Gallbladder carcinoma (advanced, surgical)",
      "Hepatic adenoma with rupture risk",
      "Focal nodular hyperplasia (surgical)",
      "Fibrolamellar hepatocellular carcinoma",
      "Cholangiocarcinoma (intrahepatic, surgical)",
      "Solid pseudopapillary tumor of pancreas",
      "Pancreatic neuroendocrine tumor (non-functioning)",
      "Glucagonoma",
      "Somatostatinoma",
      "VIPoma",
      "Carcinosarcoma of esophagus",
      "Gastric lymphoma (surgical)",
      "Duodenal gastrinoma",
      "Appendiceal mucinous neoplasm",
      "Sclerosing angiomatoid nodular transformation of spleen",
      "Littoral cell angioma of spleen",
      "Retroperitoneal fibrosis (surgical)"
    ]
  },
  "Obstetrics & Gynaecology (OBG)": {
    "common": [
      "Normal pregnancy/antenatal care conditions",
      "Anemia in pregnancy",
      "Pregnancy-induced hypertension/pre-eclampsia",
      "Gestational diabetes",
      "Menstrual disorders (menorrhagia, dysmenorrhea)",
      "Polycystic ovarian syndrome (PCOS)",
      "Uterine fibroids",
      "Vaginal/pelvic infections",
      "Postpartum hemorrhage",
      "Ectopic pregnancy",
      "Threatened/spontaneous abortion",
      "Preterm labour",
      "Urinary tract infection in pregnancy",
      "Vaginal candidiasis",
      "Bacterial vaginosis",
      "Pelvic inflammatory disease",
      "Cervical erosion/ectropion",
      "Amenorrhea (secondary)",
      "Menopausal syndrome",
      "Ovarian cyst (functional)",
      "Vulvovaginal candidiasis (recurrent)",
      "Cervicitis",
      "Endometritis",
      "Puerperal mastitis",
      "Nipple fissure/lactation issues",
      "Symphysis pubis dysfunction (pregnancy)",
      "Round ligament pain (pregnancy)",
      "Braxton Hicks contractions",
      "Hyperemesis gravidarum",
      "Linea nigra/chloasma (pregnancy skin changes)",
      "Vaginal atrophy (menopausal)",
      "Uterine polyp",
      "Cervical polyp",
      "Bartholin's cyst/abscess",
      "Vulvar dermatitis",
      "Premenstrual syndrome",
      "Anovulatory cycles",
      "Dyspareunia",
      "Vaginismus",
      "Pelvic organ prolapse (mild)"
    ],
    "lessCommon": [
      "Eclampsia",
      "Placenta previa",
      "Abruptio placentae",
      "Obstructed labour",
      "Ovarian cysts/tumors (benign)",
      "Endometriosis",
      "Infertility (female factor)",
      "Cervical intraepithelial neoplasia",
      "Molar pregnancy (hydatidiform mole)",
      "Rh isoimmunization",
      "Intrauterine growth restriction",
      "Oligohydramnios",
      "Polyhydramnios",
      "Twin pregnancy complications",
      "Postpartum sepsis (puerperal fever)",
      "Adenomyosis",
      "Uterine prolapse",
      "Premature rupture of membranes",
      "Gestational trophoblastic disease (partial mole)",
      "Fibroid degeneration (red degeneration in pregnancy)",
      "Chronic pelvic pain syndrome (gynaecological)",
      "Asherman's syndrome (lessCommon presentation)",
      "Cervical incompetence",
      "Uterine septum (surgical correlate)",
      "Recurrent pregnancy loss (immunological/anatomical)",
      "Antiphospholipid syndrome in pregnancy",
      "Gestational thrombocytopenia",
      "Acute fatty liver of pregnancy (lessCommon presentation)",
      "Chorioamnionitis",
      "Vasa previa (lessCommon variant)",
      "Cervical ectropion with bleeding",
      "Endometrial polyp with abnormal bleeding",
      "Ovarian torsion",
      "Tubo-ovarian abscess",
      "Fitz-Hugh-Curtis syndrome",
      "Premature ovarian insufficiency",
      "Turner syndrome-related gonadal dysgenesis (gynaecological)",
      "Androgen insensitivity syndrome (gynaecological)",
      "Mayer-Rokitansky-Küster-Hauser syndrome",
      "Imperforate hymen"
    ],
    "rare": [
      "Choriocarcinoma",
      "Amniotic fluid embolism",
      "Uterine rupture",
      "Vasa previa",
      "HELLP syndrome",
      "Uterine inversion",
      "Ovarian carcinoma",
      "Cervical carcinoma (advanced)",
      "Asherman's syndrome",
      "Placenta accreta/percreta",
      "Acute fatty liver of pregnancy",
      "Peripartum cardiomyopathy",
      "Sheehan syndrome",
      "Placental abruption with DIC",
      "Vulvar carcinoma",
      "Fallopian tube carcinoma",
      "Ovarian hyperstimulation syndrome",
      "Cornual (interstitial) ectopic pregnancy",
      "Uterine sarcoma",
      "Meigs syndrome",
      "Krukenberg tumor",
      "Struma ovarii",
      "Dysgerminoma",
      "Granulosa cell tumor of ovary",
      "Sertoli-Leydig cell tumor",
      "Vaginal clear cell adenocarcinoma (DES-related)",
      "Placental site trophoblastic tumor",
      "Epithelioid trophoblastic tumor",
      "Uterine arteriovenous malformation",
      "Ovarian remnant syndrome",
      "Abdominal pregnancy",
      "Heterotopic pregnancy",
      "Uterine leiomyosarcoma (advanced)",
      "Endometrial stromal sarcoma",
      "Vaginal rhabdomyosarcoma (sarcoma botryoides)",
      "Fallopian tube torsion",
      "Broad ligament fibroid with degeneration",
      "Ovarian fibroma with Meigs syndrome",
      "Peripartum hysterectomy-associated complications",
      "Uterine niche (cesarean scar defect)"
    ]
  },
  "Paediatrics": {
    "common": [
      "Acute respiratory infections",
      "Acute diarrheal disease/dehydration",
      "Protein-energy malnutrition",
      "Neonatal jaundice",
      "Vaccine-preventable diseases (measles, chickenpox)",
      "Iron deficiency anemia",
      "Febrile seizures",
      "Bronchiolitis",
      "Worm infestations",
      "Vitamin D deficiency rickets",
      "Neonatal sepsis (early presentation)",
      "Acute tonsillitis (paediatric)",
      "Croup (laryngotracheobronchitis)",
      "Hand-foot-mouth disease",
      "Impetigo (paediatric)",
      "Otitis media (paediatric)",
      "Urinary tract infection (paediatric)",
      "Failure to thrive",
      "Constipation (functional, paediatric)",
      "Atopic dermatitis (paediatric)",
      "Diaper rash (irritant dermatitis)",
      "Colic (infantile)",
      "Umbilical granuloma",
      "Breath-holding spells",
      "Nocturnal enuresis",
      "Threadworm infestation (paediatric)",
      "Head lice (paediatric)",
      "Molluscum contagiosum (paediatric)",
      "Acute otitis externa (paediatric)",
      "Teething-related symptoms",
      "Iron-deficiency-related pica",
      "Vaso-vagal syncope (paediatric)",
      "Growing pains",
      "Functional abdominal pain (paediatric)",
      "Acute lymphadenitis (paediatric)",
      "Viral exanthem (non-specific)",
      "Scarlet fever",
      "Hand dermatitis (paediatric)",
      "Allergic rhinoconjunctivitis (paediatric)",
      "Recurrent respiratory tract infection (paediatric)"
    ],
    "lessCommon": [
      "Congenital heart disease",
      "Down syndrome",
      "Nephrotic syndrome (childhood)",
      "Acute rheumatic fever",
      "Cerebral palsy",
      "Neonatal sepsis",
      "Respiratory distress syndrome (preterm)",
      "Autism spectrum disorder",
      "ADHD",
      "Thalassemia",
      "Henoch-Schönlein purpura",
      "Idiopathic thrombocytopenic purpura (childhood)",
      "Intussusception",
      "Pyloric stenosis (infantile)",
      "Hirschsprung's disease",
      "Congenital hypothyroidism",
      "G6PD deficiency (neonatal jaundice)",
      "Bronchopulmonary dysplasia",
      "Necrotizing enterocolitis",
      "Juvenile idiopathic arthritis",
      "Coeliac disease (paediatric)",
      "Cow's milk protein allergy",
      "Eosinophilic esophagitis (paediatric)",
      "Functional constipation with encopresis",
      "Juvenile dermatomyositis",
      "Henoch-Schönlein nephritis",
      "Post-streptococcal glomerulonephritis (paediatric)",
      "Wilms tumor precursor lesion (nephroblastomatosis)",
      "Langerhans cell histiocytosis (paediatric)",
      "Transient synovitis of hip",
      "Perthes disease (paediatric)",
      "Osteochondritis dissecans",
      "Juvenile myoclonic epilepsy",
      "Benign rolandic epilepsy",
      "Febrile infection-related epilepsy syndrome",
      "Acute disseminated encephalomyelitis (paediatric)",
      "Guillain-Barré syndrome (paediatric)",
      "Sydenham's chorea",
      "PANDAS (paediatric autoimmune neuropsychiatric disorder)",
      "Kawasaki disease incomplete presentation"
    ],
    "rare": [
      "Acute lymphoblastic leukemia",
      "Wilms tumor",
      "Neuroblastoma",
      "Kawasaki disease",
      "Duchenne muscular dystrophy",
      "Biliary atresia",
      "Congenital adrenal hyperplasia",
      "SCID (severe combined immunodeficiency)",
      "Reye's syndrome",
      "Hemolytic uremic syndrome",
      "Retinoblastoma (paediatric)",
      "Hepatoblastoma",
      "Rett syndrome",
      "Prader-Willi syndrome",
      "Menkes disease (paediatric)",
      "Osteogenesis imperfecta (paediatric)",
      "Spinal muscular atrophy",
      "Galactosemia (neonatal presentation)",
      "Maple syrup urine disease (neonatal)",
      "Congenital diaphragmatic hernia (neonatal)",
      "Aicardi syndrome",
      "CHARGE syndrome",
      "VACTERL association (paediatric clinical)",
      "Beckwith-Wiedemann syndrome",
      "Noonan syndrome",
      "Williams syndrome",
      "Cri-du-chat syndrome",
      "Edwards syndrome (trisomy 18)",
      "Patau syndrome (trisomy 13)",
      "Angelman syndrome",
      "Smith-Magenis syndrome",
      "Cornelia de Lange syndrome",
      "Fanconi anemia",
      "Diamond-Blackfan anemia",
      "Kostmann syndrome",
      "Wiskott-Aldrich syndrome",
      "DiGeorge syndrome (paediatric)",
      "Chronic granulomatous disease",
      "Ataxia-telangiectasia",
      "Progeria (Hutchinson-Gilford syndrome)"
    ]
  },
  "Orthopaedics": {
    "common": [
      "Fractures (long bone — femur, tibia, radius/ulna)",
      "Osteoarthritis",
      "Low back pain / disc prolapse",
      "Sprains and ligament injuries",
      "Osteoporosis",
      "Fracture clavicle",
      "Dislocation shoulder",
      "Cervical spondylosis",
      "Plantar fasciitis",
      "Frozen shoulder",
      "Tennis elbow (lateral epicondylitis)",
      "Fracture neck of femur",
      "Meniscal tear (knee)",
      "Ankle sprain",
      "Rotator cuff injury",
      "Carpal tunnel syndrome",
      "Bunion (hallux valgus)",
      "Trigger finger",
      "De Quervain's tenosynovitis",
      "Colles' fracture",
      "Fracture humerus shaft",
      "Fracture both bones forearm",
      "Fracture metacarpal (boxer's fracture)",
      "Fracture calcaneus",
      "Fracture metatarsal",
      "Achilles tendon rupture",
      "Patellar dislocation",
      "Elbow dislocation",
      "Hip dislocation (traumatic)",
      "Wrist sprain",
      "Shoulder impingement syndrome",
      "Golfer's elbow (medial epicondylitis)",
      "Iliotibial band syndrome",
      "Shin splints",
      "Hammer toe",
      "Claw toe",
      "Ingrown toenail (orthopaedic)",
      "Ganglion cyst (orthopaedic)",
      "Bursitis (olecranon/prepatellar)",
      "Spondylolisthesis"
    ],
    "lessCommon": [
      "Rheumatoid arthritis (orthopaedic aspects)",
      "Osteomyelitis",
      "Congenital talipes equinovarus (CTEV/clubfoot)",
      "Developmental dysplasia of hip (DDH)",
      "Septic arthritis",
      "Ankylosing spondylitis",
      "Avascular necrosis of femoral head",
      "Rickets/osteomalacia (orthopaedic)",
      "Scoliosis",
      "Compartment syndrome",
      "Slipped capital femoral epiphysis",
      "Osgood-Schlatter disease",
      "Tuberculosis of spine (Pott's disease)",
      "Non-union of fracture",
      "Malunion of fracture",
      "Charcot joint (neuropathic arthropathy)",
      "Torticollis (musculoskeletal)",
      "Kienböck's disease",
      "Freiberg's disease",
      "Gouty arthritis (orthopaedic)",
      "Spondylolysis",
      "Cervical disc herniation with radiculopathy",
      "Lumbar spinal stenosis",
      "Cauda equina syndrome",
      "Thoracic outlet syndrome",
      "Tarsal tunnel syndrome",
      "Peroneal nerve palsy",
      "Radial nerve palsy (orthopaedic)",
      "Ulnar nerve entrapment (cubital tunnel)",
      "Volkmann's ischemic contracture",
      "Dupuytren's contracture",
      "Plantar fibromatosis",
      "Adhesive capsulitis (severe)",
      "Snapping hip syndrome",
      "Piriformis syndrome",
      "Baker's cyst (popliteal)",
      "Chondromalacia patellae",
      "Osteochondritis dissecans (orthopaedic)",
      "Legg-Calvé-Perthes disease (orthopaedic)",
      "Blount's disease"
    ],
    "rare": [
      "Osteosarcoma",
      "Ewing's sarcoma",
      "Osteogenesis imperfecta",
      "Achondroplasia",
      "Perthes disease",
      "Marfan syndrome (skeletal)",
      "Paget's disease of bone",
      "Giant cell tumor of bone",
      "Chondrosarcoma",
      "Fibrous dysplasia",
      "Osteopetrosis",
      "Multiple hereditary exostoses",
      "Osteoid osteoma",
      "Enchondromatosis (Ollier disease)",
      "Synovial sarcoma",
      "Chordoma",
      "Adamantinoma",
      "Langerhans cell histiocytosis (bone)",
      "Melorheostosis",
      "Fibrodysplasia ossificans progressiva",
      "Multiple myeloma (orthopaedic presentation)",
      "Metastatic bone disease (orthopaedic)",
      "Osteoblastoma",
      "Aneurysmal bone cyst",
      "Unicameral bone cyst",
      "Non-ossifying fibroma",
      "Chondroblastoma",
      "Chondromyxoid fibroma",
      "Parosteal osteosarcoma",
      "Periosteal osteosarcoma",
      "Telangiectatic osteosarcoma",
      "Malignant fibrous histiocytoma of bone",
      "Liposarcoma (orthopaedic)",
      "Rhabdomyosarcoma (orthopaedic)",
      "Neurofibromatosis type 1 (orthopaedic)",
      "Camurati-Engelmann disease",
      "Hypophosphatemic rickets (orthopaedic)",
      "Renal osteodystrophy",
      "Scurvy (orthopaedic manifestations)",
      "Copper deficiency osteopathy"
    ]
  },
  "Dermatology": {
    "common": [
      "Acne vulgaris",
      "Eczema/atopic dermatitis",
      "Fungal skin infections (tinea)",
      "Scabies",
      "Urticaria",
      "Psoriasis",
      "Contact dermatitis",
      "Viral warts",
      "Vitiligo",
      "Alopecia (androgenetic/areata)",
      "Pediculosis (lice infestation)",
      "Molluscum contagiosum",
      "Impetigo",
      "Folliculitis",
      "Melasma (dermatological)",
      "Seborrheic keratosis",
      "Callus/corn",
      "Prickly heat (miliaria)",
      "Chronic hand eczema",
      "Tinea versicolor",
      "Milia",
      "Sebaceous hyperplasia",
      "Xerosis (dry skin)",
      "Perioral dermatitis",
      "Intertrigo",
      "Pompholyx (dyshidrotic eczema)",
      "Stasis dermatitis",
      "Erythema ab igne",
      "Frictional dermatitis",
      "Miliaria profunda",
      "Keratosis pilaris",
      "Ichthyosis vulgaris (mild)",
      "Sunburn (acute)",
      "Pityriasis alba",
      "Pityriasis rosea",
      "Angular cheilitis",
      "Onychomycosis",
      "Paronychia",
      "Corns/calluses (dermatological)",
      "Skin tags (acrochordon)"
    ],
    "lessCommon": [
      "Herpes zoster",
      "Lichen planus",
      "Pemphigus vulgaris",
      "Bullous pemphigoid",
      "Leprosy (dermatological)",
      "Syphilis (cutaneous manifestations)",
      "Drug eruptions (fixed drug eruption, Stevens-Johnson)",
      "Seborrheic dermatitis",
      "Rosacea",
      "Melasma",
      "Discoid lupus erythematosus",
      "Erythema nodosum",
      "Erythema multiforme",
      "Lichen sclerosus",
      "Granuloma annulare",
      "Nummular eczema",
      "Hidradenitis suppurativa",
      "Actinic keratosis",
      "Keloid/hypertrophic scar",
      "Photodermatitis",
      "Lichen simplex chronicus",
      "Prurigo nodularis",
      "Grover's disease (transient acantholytic dermatosis)",
      "Erythrasma",
      "Pitted keratolysis",
      "Livedo reticularis",
      "Panniculitis (idiopathic)",
      "Erythema annulare centrifugum",
      "Subcorneal pustular dermatosis",
      "Pyoderma faciale",
      "Perniosis (chilblains)",
      "Cutaneous larva migrans",
      "Tungiasis",
      "Cutaneous leishmaniasis",
      "Cutaneous tuberculosis (lupus vulgaris)",
      "Nodular vasculitis",
      "Livedoid vasculopathy",
      "Erythema gyratum repens",
      "Confluent and reticulated papillomatosis",
      "Flegel's disease"
    ],
    "rare": [
      "Toxic epidermal necrolysis",
      "Mycosis fungoides",
      "Xeroderma pigmentosum",
      "Epidermolysis bullosa",
      "Dermatitis herpetiformis",
      "Necrobiosis lipoidica",
      "Pyoderma gangrenosum",
      "Cutaneous T-cell lymphoma",
      "Acanthosis nigricans (paraneoplastic)",
      "Sweet syndrome",
      "Ichthyosis (congenital)",
      "Darier's disease",
      "Pemphigus foliaceus",
      "Linear IgA bullous dermatosis",
      "Porphyria cutanea tarda (dermatological)",
      "Scleroderma (cutaneous, systemic sclerosis)",
      "Necrolytic migratory erythema",
      "Kaposi sarcoma (dermatological)",
      "Erythroderma (exfoliative dermatitis)",
      "Bazex syndrome",
      "Papuloerythroderma of Ofuji",
      "Reactive perforating collagenosis",
      "Elastosis perforans serpiginosa",
      "Pseudoxanthoma elasticum",
      "Ehlers-Danlos syndrome (cutaneous)",
      "Cutis laxa",
      "Restrictive dermopathy",
      "Harlequin ichthyosis",
      "Netherton syndrome",
      "Chanarin-Dorfman syndrome",
      "Gorlin syndrome (basal cell nevus syndrome)",
      "Muir-Torre syndrome",
      "Cowden syndrome (dermatological)",
      "Peutz-Jeghers syndrome (dermatological)",
      "Birt-Hogg-Dubé syndrome",
      "Sézary syndrome",
      "Lymphomatoid papulosis",
      "Angiosarcoma (cutaneous)",
      "Merkel cell carcinoma",
      "Extramammary Paget's disease"
    ]
  },
  "Psychiatry": {
    "common": [
      "Major depressive disorder",
      "Generalized anxiety disorder",
      "Alcohol use disorder",
      "Insomnia",
      "Somatoform disorders",
      "Panic disorder",
      "Adjustment disorder",
      "Substance use disorder (tobacco/cannabis)",
      "Post-traumatic stress disorder",
      "Obsessive-compulsive disorder",
      "Specific phobia",
      "Acute stress reaction",
      "Grief reaction (complicated)",
      "Body dysmorphic disorder",
      "Eating disorder (anorexia/bulimia)",
      "Sleep disorder (parasomnias)",
      "Hypochondriasis (illness anxiety disorder)",
      "Cyclothymia",
      "Dysthymia (persistent depressive disorder)",
      "Nicotine dependence",
      "Adjustment disorder with anxiety",
      "Adjustment disorder with depressed mood",
      "Separation anxiety disorder",
      "Selective mutism",
      "Enuresis (psychiatric evaluation)",
      "Encopresis (psychiatric evaluation)",
      "Oppositional defiant disorder",
      "Conduct disorder",
      "Stuttering (psychiatric evaluation)",
      "Tic disorder (transient)",
      "Sleepwalking (somnambulism)",
      "Night terrors",
      "Nightmare disorder",
      "Bruxism (psychiatric correlate)",
      "Caffeine use disorder",
      "Internet gaming disorder",
      "Excoriation (skin-picking) disorder",
      "Illness anxiety disorder (severe)",
      "Premenstrual dysphoric disorder",
      "Postpartum blues"
    ],
    "lessCommon": [
      "Schizophrenia",
      "Bipolar affective disorder",
      "Delirium",
      "Dementia (Alzheimer's type)",
      "Social anxiety disorder / phobias",
      "Somatic symptom disorder",
      "Conversion disorder",
      "ADHD (psychiatric evaluation)",
      "Personality disorders (borderline, antisocial)",
      "Opioid dependence",
      "Delusional disorder",
      "Brief psychotic disorder",
      "Vascular dementia",
      "Frontotemporal dementia",
      "Postpartum depression/psychosis",
      "Alcohol withdrawal delirium (delirium tremens)",
      "Substance-induced psychotic disorder",
      "Trichotillomania",
      "Gambling disorder",
      "Intellectual disability (psychiatric assessment)",
      "Avoidant personality disorder",
      "Dependent personality disorder",
      "Narcissistic personality disorder",
      "Histrionic personality disorder",
      "Schizoid personality disorder",
      "Schizotypal personality disorder",
      "Paranoid personality disorder",
      "Obsessive-compulsive personality disorder",
      "Cyclothymic disorder (lessCommon presentation)",
      "Persistent complex bereavement disorder",
      "Reactive attachment disorder",
      "Disinhibited social engagement disorder",
      "Gender dysphoria",
      "Paraphilic disorders (clinical evaluation)",
      "Factitious disorder",
      "Alcohol-induced psychotic disorder",
      "Cannabis-induced psychotic disorder",
      "Stimulant-induced psychotic disorder",
      "Late-onset schizophrenia",
      "Postictal psychosis"
    ],
    "rare": [
      "Catatonia",
      "Schizoaffective disorder",
      "Capgras syndrome",
      "Cotard's syndrome",
      "Dissociative identity disorder",
      "Munchausen syndrome",
      "Folie à deux (shared psychotic disorder)",
      "Kleine-Levin syndrome",
      "Neuroleptic malignant syndrome (psychiatric context)",
      "De Clerambault syndrome (erotomania)",
      "Fregoli syndrome",
      "Ganser syndrome",
      "Charles Bonnet syndrome",
      "Othello syndrome (delusional jealousy)",
      "Ekbom syndrome (delusional parasitosis)",
      "Alien hand syndrome (psychiatric correlate)",
      "Depersonalization-derealization disorder",
      "Pica (severe/persistent)",
      "Reduplicative paramnesia",
      "Cotard-Capgras overlap syndrome",
      "Lycanthropy (clinical delusion)",
      "Clérambault-Kandinsky complex",
      "Diogenes syndrome",
      "Cotard delusion with nihilism (severe)",
      "Autoscopic phenomena (psychiatric)",
      "Reduplicative paramnesia (psychiatric, severe)",
      "Anton syndrome (psychiatric correlate)",
      "Geschwind syndrome",
      "Kluver-Bucy syndrome (psychiatric)",
      "Foreign accent syndrome",
      "Alien hand syndrome (severe psychiatric overlap)",
      "Cotard-Fregoli overlap presentation",
      "Susac syndrome (psychiatric presentation)",
      "Wilson's disease (psychiatric presentation)",
      "Anti-NMDA receptor encephalitis (psychiatric presentation)",
      "Steroid-induced psychosis (severe)",
      "Postpartum psychosis (severe)",
      "Puerperal catatonia",
      "Kleine-Levin syndrome (severe recurrent)",
      "Cotard syndrome in elderly with dementia overlap"
    ]
  },
  "Emergency Medicine": {
    "common": [
      "Acute myocardial infarction",
      "Trauma/polytrauma",
      "Acute severe asthma",
      "Anaphylaxis",
      "Diabetic ketoacidosis",
      "Acute stroke",
      "Status epilepticus",
      "Acute poisoning (organophosphate, drug overdose)",
      "Snake bite envenomation",
      "Acute gastroenteritis with dehydration",
      "Acute abdomen (general presentation)",
      "Hypertensive emergency",
      "Acute pulmonary embolism (emergency)",
      "Head injury (mild-moderate)",
      "Foreign body airway obstruction",
      "Acute urinary retention",
      "Febrile seizure (emergency presentation)",
      "Acute severe pain crisis (sickle cell)",
      "Hypoglycemia (emergency)",
      "Acute allergic reaction (non-anaphylactic)",
      "Acute chest pain (undifferentiated)",
      "Acute abdominal pain (undifferentiated)",
      "Syncope (emergency evaluation)",
      "Acute confusion/delirium (emergency)",
      "Acute back pain (emergency red flags)",
      "Minor head injury (paediatric emergency)",
      "Laceration requiring repair",
      "Corneal foreign body (emergency)",
      "Epistaxis (emergency management)",
      "Acute otitis media (emergency presentation)",
      "Acute asthma exacerbation (moderate)",
      "Acute gout flare (emergency)",
      "Acute low back pain with sciatica (emergency)",
      "Dental abscess (emergency)",
      "Acute urinary tract infection (emergency)",
      "Vaginal bleeding (emergency, non-pregnant)",
      "Minor burns (emergency management)",
      "Insect sting reaction (emergency)",
      "Foreign body ingestion (emergency)",
      "Acute vertigo (emergency evaluation)"
    ],
    "lessCommon": [
      "Cardiac arrest (arrhythmia-related)",
      "Tension pneumothorax",
      "Septic shock",
      "Burns (major)",
      "Hypoglycemic emergency",
      "Acute pulmonary edema",
      "Ectopic pregnancy rupture (emergency)",
      "Heat stroke",
      "Near-drowning",
      "Acute abdomen (perforation/obstruction)",
      "Diabetic hyperosmolar state",
      "Acute compartment syndrome (emergency)",
      "Traumatic hemothorax",
      "Acute mesenteric ischemia (emergency)",
      "Acute limb ischemia",
      "Testicular torsion (emergency)",
      "Acute epiglottitis (emergency)",
      "Severe electrolyte derangement (hyperkalemia crisis)",
      "Acute variceal bleeding",
      "Status asthmaticus",
      "Wernicke encephalopathy (emergency)",
      "Acute alcohol withdrawal (emergency)",
      "Serotonin syndrome (emergency, moderate)",
      "Acute lithium toxicity",
      "Acute salicylate toxicity",
      "Acute paracetamol (acetaminophen) overdose",
      "Acute tricyclic antidepressant overdose",
      "Acute beta-blocker overdose",
      "Acute calcium channel blocker overdose",
      "Acute digoxin toxicity (emergency)",
      "Acute carbon monoxide poisoning (emergency)",
      "Acute methanol/ethylene glycol poisoning (emergency)",
      "Acute anaphylactic shock (emergency)",
      "Acute angioedema (emergency airway risk)",
      "Acute necrotizing pancreatitis (emergency)",
      "Acute cholangitis (emergency)",
      "Acute epididymo-orchitis (emergency)",
      "Acute priapism (emergency)",
      "Acute compartment syndrome (forearm, emergency)",
      "Acute retinal artery occlusion (emergency)"
    ],
    "rare": [
      "Massive pulmonary embolism",
      "Aortic dissection",
      "Amniotic fluid embolism (emergency)",
      "Thyroid storm",
      "Myxedema coma",
      "Addisonian crisis",
      "Malignant hyperthermia (emergency)",
      "Neuroleptic malignant syndrome (emergency)",
      "Mass casualty/disaster trauma",
      "Electrical injury with cardiac arrest",
      "Cardiac tamponade (emergency)",
      "Necrotizing fasciitis (emergency)",
      "Traumatic aortic rupture",
      "Fat embolism syndrome",
      "Serotonin syndrome (emergency)",
      "Anaphylactoid reaction to contrast media",
      "Air embolism (emergency)",
      "Toxic shock syndrome",
      "Ruptured abdominal aortic aneurysm",
      "Spontaneous pneumomediastinum",
      "Acute aortic occlusion (saddle embolus)",
      "Spontaneous coronary artery dissection",
      "Acute Boerhaave syndrome (emergency)",
      "Acute necrotizing pancreatitis with sepsis",
      "Purpura fulminans",
      "Waterhouse-Friderichsen syndrome",
      "Acute disseminated intravascular coagulation (emergency)",
      "Acute thyroid storm with cardiac collapse",
      "Acute pheochromocytoma crisis",
      "Acute myasthenic crisis",
      "Acute Guillain-Barré with respiratory failure",
      "Acute spinal cord compression (emergency)",
      "Acute hyperammonemic encephalopathy",
      "Acute methemoglobinemia (emergency)",
      "Acute cyanide poisoning (emergency)",
      "Acute organophosphate crisis with cholinergic storm",
      "Acute snake envenomation with coagulopathy (emergency)",
      "Acute black widow spider envenomation",
      "Acute scorpion sting with cardiotoxicity",
      "Acute box jellyfish envenomation"
    ]
  }
};

if (typeof module !== 'undefined' && module.exports) module.exports = DISEASES;
