// concepts-signs.js
// Concept pool of examination signs used in disease profiles, keyed by id.
// This is separate from clinical-findings-data.js (the large browsable sign/
// system reference list) — this pool only holds signs actually wired into a
// disease profile, so it doubles as the node list for the signs side of the graph.
// TO ADD: reuse an existing id if the same sign applies elsewhere; otherwise add one.

const SIGNS = {
  "mcburneys-point-tenderness": "McBurney's point tenderness",
  "rovsings-sign": "Rovsing's sign",
  "psoas-sign": "Psoas sign",
  "obturator-sign": "Obturator sign",
  "rebound-tenderness": "Rebound tenderness",
  "guarding": "Guarding",
  "levines-sign": "Levine's sign",
  "third-heart-sound-s3-gallop": "Third heart sound (S3 gallop)",
  "bradycardia": "Bradycardia",
  "hypotension": "Hypotension",
  "raised-jugular-venous-pressure": "Raised jugular venous pressure",
  "coarse-crackles": "Coarse crackles",
  "bronchial-breathing": "Bronchial breathing",
  "digital-clubbing-respiratory-cause": "Digital clubbing (respiratory cause)",
  "cachexia": "Cachexia",
  "fever": "Fever",
  "acanthosis-nigricans": "Acanthosis nigricans",
  "delayed-capillary-refill": "Delayed capillary refill",
  "peripheral-edema": "Peripheral edema",
  "xerosis-dry-skin": "Xerosis (dry skin)",
  "dull-percussion-note": "Dull percussion note",
  "increased-tactile-fremitus": "Increased tactile fremitus",
  "egophony": "Egophony",
  "tachypnea": "Tachypnea",
  "pallor": "Pallor",
  "hypertension": "Hypertension",
  "uremic-fetor": "Uremic fetor",
  "anasarca": "Anasarca",
  "kernigs-sign": "Kernig's sign",
  "brudzinskis-sign": "Brudzinski's sign",
  "altered-mental-status": "Altered mental status",
  "petechial-rash-meningococcemia": "Petechial rash (meningococcemia)",
  "spider-angiomata": "Spider angiomata",
  "palmar-erythema": "Palmar erythema",
  "jaundice": "Jaundice",
  "asterixis": "Asterixis",
  "caput-medusae": "Caput medusae",
  "ascites": "Ascites",
  "swan-neck-deformity": "Swan neck deformity",
  "boutonniere-deformity": "Boutonniere deformity",
  "ulnar-deviation": "Ulnar deviation",
  "rheumatoid-nodules": "Rheumatoid nodules",
  "joint-swelling-symmetric": "Joint swelling (symmetric)",
  "facial-asymmetry": "Facial asymmetry",
  "hemiparesis": "Hemiparesis",
  "babinski-sign-extensor": "Babinski sign (extensor)",
  "dysarthria": "Dysarthria",
  "cough-impulse-positive": "Cough impulse (positive)",
  "reducible-groin-swelling": "Reducible groin swelling",
  "unable-to-get-above-the-swelling": "Unable to get above the swelling",
  "deep-ring-occlusion-test": "Deep ring occlusion test (differentiates direct/indirect hernia)",
  "dilated-tortuous-superficial-veins": "Dilated, tortuous superficial veins",
  "trendelenburg-test-positive": "Trendelenburg test positive",
  "varicose-eczema-hyperpigmentation": "Varicose eczema/hyperpigmentation",
  "saphena-varix": "Saphena varix",
  "palpable-supraclavicular-bony-mass": "Palpable supraclavicular bony mass",
  "adsons-test-positive": "Adson's test positive",
  "radial-pulse-diminished-on-arm-abduction": "Radial pulse diminished on arm abduction",
  "supraclavicular-bruit": "Supraclavicular bruit",
  "visible-cleft-of-lip-and-or-palate": "Visible cleft of lip and/or palate",
  "recurrent-otitis-media-eustachian-dysfunction": "Recurrent otitis media (Eustachian tube dysfunction)",
  "non-palpable-or-palpable-undescended-testis-in-inguinal-canal": "Non-palpable or palpable undescended testis (inguinal canal)",
  "hypoplastic-scrotum-on-affected-side": "Hypoplastic scrotum on affected side",
  "midline-lumbosacral-skin-stigmata-dimple-hair-tuft-lipoma": "Midline lumbosacral skin stigmata (dimple, hair tuft, lipoma)",
  "foot-deformity-in-tethered-cord": "Foot deformity (tethered cord)",
  "accessory-nipple-or-glandular-tissue-along-milk-line": "Accessory nipple or glandular tissue along milk line",
  "loss-of-medial-longitudinal-arch-on-standing": "Loss of medial longitudinal arch on standing",
  "too-many-toes-sign": "Too many toes sign",
  "single-heel-raise-test-abnormal": "Single heel raise test (abnormal)",
  "depressed-sternum-and-costal-cartilages": "Depressed sternum and costal cartilages",
  "displaced-apex-beat": "Displaced apex beat",
  "protruding-sternum-and-costal-cartilages": "Protruding sternum and costal cartilages",
  "reducible-umbilical-swelling": "Reducible umbilical swelling",
  "transillumination-positive": "Transillumination positive",
  "able-to-get-above-the-scrotal-swelling": "Able to get above the scrotal swelling",
  "midline-neck-mass-elevates-with-tongue-protrusion": "Midline neck mass that elevates with tongue protrusion",
  "palpable-abdominal-or-pelvic-mass-ectopic-kidney": "Palpable abdominal or pelvic mass (ectopic kidney)",
  "bifid-or-cleft-uvula-on-oral-examination": "Bifid or cleft uvula on oral examination",
  "zona-pellucida-notch-in-posterior-hard-palate": "Zona pellucida/notch in posterior hard palate (submucous cleft sign)",
  "positive-barlow-test": "Positive Barlow test",
  "positive-ortolani-test": "Positive Ortolani test",
  "limited-hip-abduction-in-flexion": "Limited hip abduction in flexion",
  "asymmetric-thigh-skin-folds": "Asymmetric thigh skin folds",
  "visible-full-thickness-rectal-protrusion-on-straining": "Visible full-thickness rectal protrusion on straining",
  "concentric-mucosal-folds-on-prolapsed-rectum": "Concentric mucosal folds on prolapsed rectum",
  "reduced-anal-sphincter-tone": "Reduced anal sphincter tone",
  "palpable-inter-recti-gap-on-abdominal-crunch": "Palpable inter-recti gap on abdominal crunch",
  "visible-midline-doming-on-straining": "Visible midline doming on straining",
  "short-thick-lingual-frenulum": "Short, thick lingual frenulum",
  "restricted-tongue-tip-protrusion-heart-shaped-tongue": "Restricted tongue-tip protrusion (heart-shaped tongue)",
  "bilateral-skin-webbing-from-mastoid-to-acromion": "Bilateral skin webbing from mastoid to acromion",
  "low-posterior-hairline": "Low posterior hairline",
  "single-transverse-palmar-crease": "Single transverse palmar crease",
  "pigmented-papule-or-nodule-along-milk-line": "Pigmented papule or nodule along the milk line",
  "may-mimic-nevus-or-skin-tag": "May mimic a nevus or skin tag",
  "continuous-urinary-dribbling-incontinence-ectopic-ureter": "Continuous urinary dribbling/incontinence (ectopic ureter insertion)",
  "atypical-tenderness-in-right-flank-or-loin": "Atypical tenderness in right flank or loin",
  "flexed-resting-posture-of-distal-interphalangeal-joint": "Flexed resting posture of the distal interphalangeal joint",
  "extensor-lag-at-dip-joint": "Extensor lag at the DIP joint",
  "palpable-nodule-notta-node-at-a1-pulley": "Palpable nodule (Notta's node) at the A1 pulley",
  "fixed-flexion-deformity-of-thumb-ip-joint": "Fixed flexion deformity of the thumb IP joint",
  "reduced-lumbosacral-segment-mobility": "Reduced lumbosacral segment mobility",
  "smooth-fluctuant-lateral-neck-swelling": "Smooth, fluctuant lateral neck swelling",
  "sinus-opening-with-mucoid-discharge-lateral-neck": "Sinus opening with mucoid discharge on lateral neck",
  "small-pit-or-tag-anterior-to-helix-of-ear": "Small pit or skin tag anterior to the helix of the ear",
  "midline-abdominal-mass-crossing-vertebral-column": "Midline abdominal mass crossing the vertebral column",
  "bony-midline-hard-palate-swelling": "Bony, midline hard-palate swelling",
  "ejection-systolic-murmur-aortic-area": "Ejection systolic murmur in the aortic area",
  "ejection-click-aortic": "Aortic ejection click",
  "melena-or-hematochezia-on-examination": "Melena or hematochezia on examination",
  "moist-umbilicus-with-urine-discharge": "Moist umbilicus with urine discharge",
  "inability-to-pass-nasogastric-tube-into-stomach": "Inability to pass a nasogastric tube into the stomach",
  "abdominal-distension-with-air-tef": "Abdominal distension with air (tracheoesophageal fistula)",
  "inability-to-pass-catheter-through-nostril": "Inability to pass a catheter through the nostril",
  "elevated-and-medially-rotated-scapula": "Elevated and medially rotated scapula",
  "apex-beat-palpable-on-right-side-dextrocardia": "Apex beat palpable on the right side (dextrocardia)",
  "liver-dullness-on-left-spleen-on-right": "Liver dullness on the left, splenic dullness on the right",
  "soft-compressible-transilluminant-neck-mass": "Soft, compressible, transilluminant neck mass",
  "palpable-left-upper-quadrant-mass-rare": "Palpable left upper quadrant mass (rare)",
  "expiratory-wheeze-widespread": "Widespread expiratory wheeze",
  "prolonged-expiratory-phase": "Prolonged expiratory phase",
  "hyperinflated-chest": "Hyperinflated chest (hyperresonant)",
  "reduced-peak-expiratory-flow": "Reduced peak expiratory flow",
  "epigastric-tenderness": "Epigastric tenderness",
  "suprapubic-tenderness": "Suprapubic tenderness",
  "renal-angle-tenderness": "Renal angle tenderness",
  "bradycardia-hypothyroid": "Bradycardia",
  "non-pitting-edema-myxedema": "Non-pitting edema (myxedema)",
  "coarse-dry-skin-and-hair-loss": "Coarse, dry skin and hair loss",
  "delayed-relaxation-of-ankle-reflex": "Delayed relaxation phase of ankle jerk",
  "diffuse-goiter": "Diffuse goiter",
  "bony-swelling-of-joint-heberden-bouchard-nodes": "Bony swelling of joint (Heberden's/Bouchard's nodes)",
  "crepitus-on-joint-movement": "Crepitus on joint movement",
  "joint-line-tenderness": "Joint line tenderness",
  "antalgic-gait": "Antalgic gait",
  "elevated-blood-pressure-reading": "Elevated blood pressure reading (≥ 140/90 mmHg)",
  "fourth-heart-sound-s4": "Fourth heart sound (S4)",
  "hypertensive-retinopathy-on-fundoscopy": "Hypertensive retinopathy on fundoscopy",
  "barrel-chest-copd": "Barrel chest",
  "pursed-lip-breathing-sign": "Pursed-lip breathing",
  "use-of-accessory-muscles-of-respiration": "Use of accessory muscles of respiration",
  "reduced-breath-sounds-copd": "Reduced breath sounds",
  "koilonychia-sign": "Koilonychia (spoon-shaped nails)",
  "angular-stomatitis": "Angular stomatitis",
  "atrophic-glossitis": "Atrophic glossitis",
  "tachycardia-anemia": "Tachycardia",
  "normal-neurological-examination-between-attacks": "Normal neurological examination between attacks (migraine)",
  "dry-mucous-membranes": "Dry mucous membranes",
  "reduced-skin-turgor": "Reduced skin turgor",
  "sunken-eyes-dehydration": "Sunken eyes",
  "diffuse-abdominal-tenderness-mild": "Diffuse mild abdominal tenderness"
};
